### ISSUE TITLE
Unknown props

### ISSUE THREAD

**Issue by wollld** [necolas/react-native-web#393] opened 2017-03-15 10:39 UTC
bundle.js:44292 Warning: Unknown props `dataSource`, `renderRow`, `renderHeader`, `renderFooter`, `enableEmptySections`, `initialListSize`, `pageSize`, `scrollRenderAheadDistance`, `onEndReachedThreshold`, `stickyHeaderIndices`, `onKeyboardWillShow`, `onKeyboardWillHide`, `onKeyboardDidShow`, `onKeyboardDidHide` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by View)
    in View (created by ScrollViewBase)
    in ScrollViewBase (created by ScrollView)
    in ScrollView (created by ListView)
    in ListView (created by TaskStatus)
    in div (created by View)
    in View (created by TaskStatus)
    in TaskStatus (created by Root(TaskStatus))
    in SiblingContainer (created by Root(TaskStatus))
    in div (created by View)
    in View (created by Root(TaskStatus))
    in Root(TaskStatus) (created by ReactNativeApp)
    in div (created by View)
    in View (created by ReactNativeApp)
    in ReactNativeApp

OS: 
Device: mac
Browser:chrome
React Native for Web (version): 0.0.77
React (version): 15.4.1

**Comment by wollld** [comment] 2017-03-15 10:40
use in
 <ListView
                            dataSource = {this.ds.cloneWithRows(this.state.taskList)}
                            renderRow = {this.renderRow}
                            renderHeader= {this.renderHeader}
                            renderFooter={this.renderFooter}
                            enableEmptySections= {true}
                            onScroll={this._onScroll}
                            {...this._panResponder.panHandlers}
                        />

**Comment by wollld** [comment] 2017-03-15 10:41
'\<ListView
                            dataSource = {this.ds.cloneWithRows(this.state.taskList)}
                            renderRow = {this.renderRow}
                            renderHeader= {this.renderHeader}
                            renderFooter={this.renderFooter}
                            enableEmptySections= {true}
                            onScroll={this._onScroll}
                            {...this._panResponder.panHandlers}
                        /\>'

**Comment by cpunion** [comment] 2017-03-16 02:48
Same problem on View:

```
Warning: Unknown props `onStartShouldSetResponder`, `onStartShouldSetResponderCapture`, `onScrollShouldSetResponder`, `onResponderGrant`, `onResponderTerminationRequest`, `onResponderTerminate`, `onResponderRelease`, `onResponderReject` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by View)
    in View (created by ScrollViewBase)
    in ScrollViewBase (created by ScrollView)
    in ScrollView (at ComponentList.js:34)
```

**Comment by necolas** [comment] 2017-03-16 02:50
I can't reproduce

**Comment by necolas** [comment] 2017-03-16 02:50
Also, make sure you're using the supported version of react

**Comment by cpunion** [comment] 2017-03-16 03:05
It's the problem in ScrollView above, seems react@16 add some props checking.

Just a warning, and it works fine in react@15.

**Comment by cpunion** [comment] 2017-03-16 03:08
Created a repo to reproduce https://github.com/cpunion/TestUnknownPropsOfScrollView

**Comment by cpunion** [comment] 2017-03-16 03:11
I repreduced @wollld 's problem in https://github.com/cpunion/TestUnknownPropsOfScrollView , install react@15.4.1 and react-dom@15.4.1 and run:

```
warning.js:36 Warning: Unknown props `onStartShouldSetResponder`, `onStartShouldSetResponderCapture`, `onScrollShouldSetResponder`, `onResponderGrant`, `onResponderTerminationRequest`, `onResponderTerminate`, `onResponderRelease`, `onResponderReject` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by View)
    in View (created by ScrollViewBase)
    in ScrollViewBase (created by ScrollView)
    in ScrollView (at App.js:17)
    in div (at App.js:9)
    in App (at index.js:7)
```

**Comment by wollld** [comment] 2017-03-16 06:06
what can i do

**Comment by necolas** [comment] 2017-03-17 20:56
I cloned that repo, npm install, npm start and I see no warnings in the console

**Comment by necolas** [comment] 2017-03-17 20:57
Going to close this until there is enough information for me to reproduce an issue

**Closed by necolas** 2017-03-17 20:57 UTC
Labels: needs more information

**Comment by cpunion** [comment] 2017-03-18 00:28
Resolved. Has two version of react/react-dom when downgrade from 16.0.0-alpha.3, 15.4.1 and 15.4.2, 
@wollld you can try removing node_modules and then npm install.

Thanks @necolas
