### ISSUE TITLE
TouchableOpacity onPress doesn't fire every time

### ISSUE THREAD

**Issue by anija** [necolas/react-native-web#1564] opened 2020-03-13 15:42 UTC
Hi,

i've noticed that the event onPress on TouchableOpacity is not firing every time. If the click is fast enough, it doesn't fire.
This wasn't happening on 0.11.x releases.

**Comment by christophemarois** [comment] 2020-03-23 19:09
Also noticed this issue!

**Comment by Hinkapie** [comment] 2020-03-25 02:55
I also noticed

**Comment by DennisOosterling** [comment] 2020-03-27 14:36
This is actually reproducible by dragging while clicking. Even it is a very small change of pointer position (even within the button) the onPress will not be triggered. If you stay on exactly the same position and click it gets triggered every time.

**Comment by anija** [comment] 2020-03-27 15:15
I'm happy to see i'm not alone.

Only to me this seems a blocking issue?
After 14 days no one of the mantainers of this repo has ever seen this topic?

**Comment by javascripter** [comment] 2020-04-06 06:39
I ended up using `onClick` instead of `onPress` for `Touchables`. This is just a  workaround  and not a proper solution because it doesn't interact with the responder system.
Hopefully this will be fixed with the Responder system rewrite?

```
<TouchableOpacity onClick={() => {} />
```

**Comment by necolas** [comment] 2020-04-09 17:01
There's a reason why I provide an issue template and it's because I need an the info the template asks for to help debug issues. Please fill it out

**Comment by javascripter** [comment] 2020-04-10 14:17
I'm still trying to find a minimal reproducible example but my case is the same as what DennisOosterling described.

In my observation the problem (button losing pressed state when pointer moves very slightly) only occurs when the  page is scrolled down at least a  little. When the  page is at the top, buttons work normally. My websites uses body scrolling, but not too sure if it's related

**Comment by javascripter** [comment] 2020-04-10 14:35
I have filled  out the  template. Hope this helps.
**The problem**

A small change in the pointer position causes the TouchableOpacity button to lose its active (pressed) state
while the button is being pressed. It's 


**How to reproduce**

https://codesandbox.io/s/elastic-almeida-rjqte

Steps to reproduce:
1. Scroll down to see the buttons
2. Press  the button
3. While the button is  being pressed down, move the pointer slightly to the
4. The  button loses its pressed state even while the pointer is inside the button.

**Expected behavior**

The button keeps its pressed state when the curosor is inside the button or when the curosor moves out of the button and then moves back inside the button.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.12.2
* React (version): 16.12.0
* Browser:
Google Chrome: Version 80.0.3987.163 (Official Build) (64-bit)
Safari: Version 13.0.5 (15608.5.11)

I only tested with the above but may happen with other browsers.

**Comment by necolas** [comment] 2020-04-10 15:39
If the page is scrolled the press should be cancelled, so if that's what it happening it is correct behavior both for RN and vanilla JS

**Comment by javascripter** [comment] 2020-04-10 15:54
I think that is not the issue I described above. The problem is not that while I'm scrolling down the button gets cancelled, but the button is cancelled immediately when the body has scrollTop > like 50 or something and pointer moves very slightly while pressing the button.

When the body scrollTop is like > 500px
https://gyazo.com/329f99d01036b7dacb30ddf0f51b3ac3

When body scrollTop is 0
https://gyazo.com/a502a34a529eb057dabd2317fdd84066

You can seebuttons behave differently.

**Comment by DennisOosterling** [comment] 2020-04-10 15:55
There does seem to be a difference between onClick & onPress behaviour. I created another codepen and gif the show the issue we're experiencing. (The gif is taken on the output of the code in the codepen).

When the view is not scrollable, the Touchable components work fine.

[![Image from Gyazo](https://i.gyazo.com/2998eeda5ec88cb33ca4296b4ba092ab.gif)](https://gyazo.com/2998eeda5ec88cb33ca4296b4ba092ab)

https://codesandbox.io/s/sad-galois-999w5?file=/src/App.js:333-399

**Comment by necolas** [comment] 2020-04-10 16:16
> the button is cancelled immediately when the body has scrollTop > like 50 or something and pointer moves very slightly while pressing the button

Yes that's a known issue too and it's due to how RN implemented Touchable by measuring the rect of the button. Rewrite of that code is the solution as per https://github.com/necolas/react-native-web/issues/1538

**Comment by necolas** [comment] 2020-04-12 19:53
Please try version `0.0.0-33f8505d6` (a canary release) and let me know if the problem is resolved. See  #1538

**Comment by javascripter** [comment] 2020-04-17 17:06
Thanks for maintaining this wonderful framework. Buttons are now working correctly for me.
Tested with react-native-web `0.0.0-87ea51c19`.

**Closed** 2020-06-26 21:56 UTC
