### ISSUE TITLE
TypeError: t.split is not a function. (In 't.split(/\s/)', 't.split' is undefined)

### ISSUE THREAD

**Issue by ahmaddehnavi** [necolas/react-native-web#2081] opened 2021-07-04 10:37 UTC
**The problem**
I got some crash reports with the following stack trace
```
File ../node_modules/inline-style-prefixer/lib/plugins/flexboxIE.js line 54 col 28 in flexboxIE
var flexValues = value.split(/\s/); // If we only have a single value that wasn't a positive ...
File ../node_modules/inline-style-prefixer/lib/utils/prefixValue.js line 10 col 34 in prefixValue
var processedValue = plugins[i](property, value, style, metaData); // we can stop processing ...
File ../node_modules/inline-style-prefixer/lib/createPrefixer.js line 53 col 49 in createPrefixer
var _processedValue = (0, _prefixValue2.default)(plugins, property, value, style, prefixM...
File ../node_modules/react-native-web/dist/modules/prefixStyles/index.js line 13 col 24 in prefixInlineStyles
var prefixedStyles = prefixAll(style); // React@15 removed undocumented support for fallback va...
File ../node_modules/react-native-web/dist/exports/StyleSheet/createStyleResolver.js line 230 col 21 in createStyleResolver
props.style = inline(props.style);
File ../node_modules/react-native-web/dist/exports/StyleSheet/createStyleResolver.js line 129 col 15 in createStyleResolver
props = _resolveStyle(style);
File ../node_modules/react-native-web/dist/modules/createDOMProps/index.js line 417 col 45 in createDOMProps
var _styleResolver$resolv = styleResolver.resolve(reactNativeStyle, finalClassList),
File ../node_modules/react-native-web/dist/exports/createElement/index.js line 22 col 18 in createElement
var domProps = createDOMProps(Component, props);
File ../node_modules/react-dom/cjs/react-dom.production.min.js line 3667 col 7 in Ya
a = c(d, e);
File ../node_modules/react-dom/cjs/react-dom.production.min.js line 4254 col 7 in Di
d = oh(a, b, c, d, f, e);
File ../node_modules/react-dom/cjs/react-dom.production.min.js line 6150 col 11 in lu
var b = Rj(a.alternate, a, U);
File ../node_modules/react-dom/cjs/react-dom.production.min.js line 6139 col 9 in su
X = Qj(X);
File ../node_modules/react-dom/cjs/react-dom.production.min.js line 5880 col 9 in $s
Kj();
File [native code] line (unknown) in $s
File ../node_modules/react-dom/cjs/react-dom.production.min.js line 2851 col 17 in [anonymous]
c = c(!0);
File ../node_modules/scheduler/cjs/scheduler.production.min.js line 309 col 12 in unstable_runWithPriority
return b();
File ../node_modules/react-dom/cjs/react-dom.production.min.js line 2846 col 7 in Go
cg(99, function () {
File ../node_modules/react-dom/cjs/react-dom.production.min.js line 2836 col 3 in Uo
fg();
File ../node_modules/react-dom/cjs/react-dom.production.min.js line 5910 col 5 in [anonymous]
gg();
File ../node_modules/react-dom/cjs/react-dom.production.min.js line 7270 col 33 in L
(W & (1 | fj | gj)) === V && (Lj(), Dj());
File ../node_modules/react-dom/cjs/react-dom.production.min.js line 192 col 35 in q
if (null !== Aa || null !== Ba) Ha(), Ea();
File ../node_modules/react-dom/cjs/react-dom.production.min.js line 202 col 14 in V
Ka = !1, La();
File ../node_modules/react-dom/cjs/react-dom.production.min.js line 1378 col 5 in Zt
Ma(sc, a);
File ../node_modules/react-dom/cjs/react-dom.production.min.js line 1341 col 13 in Jt
var e = Rc(a, b, c, d);
File [native code] line (unknown) in Jt
File ../node_modules/scheduler/cjs/scheduler.production.min.js line 309 col 12 in unstable_runWithPriority
return b();
File ../node_modules/react-dom/cjs/react-dom.production.min.js line 7263 col 12 in N
return cg(98, a.bind(null, b, c, d, e));
File ../node_modules/react-dom/cjs/react-dom.production.min.js line 1329 col 5 in Qt
Ga(e, a, b, c, d);
File [native code] line (unknown) in Qt

```

and  this
```
TypeError: t.split is not a function. (In 't.split(/\s/)', 't.split' is undefined)
1
File "../node_modules/inline-style-prefixer/lib/plugins/flexboxIE.js" line 54 col 28 in flexboxIE
var flexValues = value.split(/\s/); // If we only have a single value that wasn't a positive ...
2
File "../node_modules/inline-style-prefixer/lib/utils/prefixValue.js" line 10 col 34 in prefixValue
var processedValue = plugins[i](property, value, style, metaData); // we can stop processing ...
3
File "../node_modules/inline-style-prefixer/lib/createPrefixer.js" line 53 col 49 in createPrefixer
var _processedValue = (0, _prefixValue2.default)(plugins, property, value, style, prefixM...
4
File "../node_modules/react-native-web/dist/modules/prefixStyles/index.js" line 13 col 24 in prefixInlineStyles
var prefixedStyles = prefixAll(style); // React@15 removed undocumented support for fallback va...
5
File "../node_modules/react-native-web/dist/exports/StyleSheet/createStyleResolver.js" line 230 col 21 in createStyleResolver
props.style = inline(props.style);
6
File "../node_modules/react-native-web/dist/exports/StyleSheet/createStyleResolver.js" line 154 col 15 in createStyleResolver
props = _resolveStyle(flatArray, _key);
7
File "../node_modules/react-native-web/dist/modules/createDOMProps/index.js" line 417 col 45 in createDOMProps
var _styleResolver$resolv = styleResolver.resolve(reactNativeStyle, finalClassList),
8
File "../node_modules/react-native-web/dist/modules/usePlatformMethods/index.js" line 67 col 20 in setNativeProps
var domProps = createDOMProps(null, _objectSpread(_objectSpread({
9
File "../node_modules/react-native-web/dist/modules/usePlatformMethods/index.js" line 131 col 11 in usePlatformMethods
setNativeProps(hostNode, nativeProps, classList, pointerEvents, style, previousStyleRef);
10
File "../node_modules/react-native-web/dist/vendor/react-native/Animated/createAnimatedComponent.js" line 189 col 28 in createAnimatedComponent
_this._component.setNativeProps(_this._propsAnimated.__getAnimatedValue());
11
File "../node_modules/react-native-web/dist/vendor/react-native/Animated/nodes/AnimatedProps.js" line 171 col 10 in [anonymous]
this._callback();
12
File "[native code]" line (unknown) in forEach
13
File "../node_modules/react-native-web/dist/vendor/react-native/Animated/nodes/AnimatedValue.js" line 73 col 18 in _flush
animatedStyles.forEach(function (animatedStyle) {
14
File "../node_modules/react-native-web/dist/vendor/react-native/Animated/nodes/AnimatedValue.js" line 299 col 7 in [anonymous]
_flush(this);
15
File "../node_modules/react-native-web/dist/vendor/react-native/Animated/nodes/AnimatedValue.js" line 259 col 14 in [anonymous]
_this3._updateValue(value, true
16
File "../node_modules/react-native-web/dist/vendor/react-native/Animated/animations/SpringAnimation.js" line 225 col 10 in [anonymous]
this._onUpdate(position);
```

```
TypeError: t.split is not a function
1
File "../node_modules/inline-style-prefixer/lib/plugins/flexboxIE.js" line 54 col 28 in flexboxIE
var flexValues = value.split(/\s/); // If we only have a single value that wasn't a positive ...
2
File "../node_modules/inline-style-prefixer/lib/utils/prefixValue.js" line 10 col 34 in prefixValue
var processedValue = plugins[i](property, value, style, metaData); // we can stop processing ...
3
File "../node_modules/inline-style-prefixer/lib/createPrefixer.js" line 53 col 49 in createPrefixer
var _processedValue = (0, _prefixValue2.default)(plugins, property, value, style, prefixM...
4
File "../node_modules/react-native-web/dist/modules/prefixStyles/index.js" line 13 col 24 in prefixInlineStyles
var prefixedStyles = prefixAll(style); // React@15 removed undocumented support for fallback va...
5
File "../node_modules/react-native-web/dist/exports/StyleSheet/compile.js" line 168 col 10 in inline
return prefixInlineStyles(createReactDOMStyle(style));
6
File "../node_modules/react-native-web/dist/exports/StyleSheet/createStyleResolver.js" line 230 col 21 in createStyleResolver
props.style = inline(props.style);
7
File "../node_modules/react-native-web/dist/exports/StyleSheet/createStyleResolver.js" line 129 col 15 in createStyleResolver
props = _resolveStyle(style);
8
File "../node_modules/react-native-web/dist/modules/createDOMProps/index.js" line 417 col 45 in createDOMProps
var _styleResolver$resolv = styleResolver.resolve(reactNativeStyle, finalClassList),
9
File "../node_modules/react-native-web/dist/exports/createElement/index.js" line 22 col 18 in createElement
var domProps = createDOMProps(Component, props);
10
File "../node_modules/react-native-web/dist/exports/View/index.js" line 164 col 10 in [anonymous]
return createElement(component, supportedProps);

```

**How to reproduce**
I couldn't reproduce it yet, but it mostly happened on mobile safari
![Screen Shot 2021-07-04 at 2 56 09 PM](https://user-images.githubusercontent.com/2734096/124381492-1fd48480-dcd8-11eb-9042-0e15cb8f9ca2.png)

**Expected behavior**
to not crash

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version):  "0.17.0"
* React (version): TBC: 17.0.2
* Browser: TBC

installed inline-style-prefixer version
"inline-style-prefixer": "6.0.0"

**Comment by ahmaddehnavi** [comment] 2021-07-04 12:39
one of this crash was related to an Animated.View and 
```
 flex: this.animatedValue.interpolate({
                                inputRange: [0, 1],
                                outputRange: [0, 1],
                            }),
```
and sometimes it produces a negative number which causes the crash as the negative float number (-0.015722281753129314 is my case) was not detected as a number by the regex check.

```
if (isUnitlessNumber.test(value))
```
```
....

var isUnitlessNumber = /^\d+(\.\d+)?$/;

function flexboxIE(property, value, style) {
  if (Object.prototype.hasOwnProperty.call(alternativeProps, property)) {
    style[alternativeProps[property]] = alternativeValues[value] || value;
  }

  if (property === 'flex') {
    // For certain values we can do straight mappings based on the spec
    // for the expansions.
    if (Object.prototype.hasOwnProperty.call(flexShorthandMappings, value)) {
      style.msFlex = flexShorthandMappings[value];
      return;
    } // Here we have no direct mapping, so we favor looking for a
    // unitless positive number as that will be the most common use-case.


    if (isUnitlessNumber.test(value)) {
      style.msFlex = value + ' 1 0%';
      return;
    } // The next thing we can look for is if there are multiple values.


    var flexValues = value.split(/\s/); // If we only have a single value that wasn't a positive unitless
    // or a pre-mapped value, then we can assume it is a unit value.

```

**Comment by necolas** [comment] 2021-07-20 17:40
I see the issue is reported upstream. And not passing negative values avoids the upstream crash. So will close this issue. Thanks

**Closed by necolas** 2021-07-20 17:40 UTC

**Comment by aryasadeghy** [comment] 2021-09-05 05:58
same issue here

**Comment by aryasadeghy** [comment] 2021-09-05 05:59
@necolas it's not possible to find out that where is that negative value is coming
