### ISSUE TITLE
Nested Text tags inside Textinput not working as expected

### ISSUE THREAD

**Issue by shakeabi** [necolas/react-native-web#1380] opened 2019-06-25 06:45 UTC
**The problem**

Nested Text tags inside Textinput not working as expected. In react native we can have inline styling inside TextInput. However, this is not reflected in react-native-web.

**How to reproduce**

Simplified test case: [link](https://codesandbox.io/embed/issue-react-native-for-web-bnklj)

Steps to reproduce:
1. Add a TextInput
2. Add multiple Text tags inside it

**Expected behavior**

This works perfectly on native (Expo: [link](https://snack.expo.io/@adarshpatel509/nested-text-inside-textinput))

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.9.3
* React (version): 16.8.6
* Browser: Chrome
No, It did not work on previous versions either.

**Comment by shakeabi** [comment] 2019-06-27 09:35
This can be fixed by replacing textarea and input with div(content-editable) tags. Any thoughts?

**Comment by necolas** [comment] 2019-06-27 17:53
Duplicate of #1023

**Closed by necolas** 2019-06-27 17:53 UTC
