### ISSUE TITLE
resolveAssetSource missing export

### ISSUE THREAD

**Issue by adids1221** [necolas/react-native-web#2509] opened 2023-04-16 12:08 UTC
### Is there an existing request?

- [X] I have searched for this request

### Describe the feature request

Hi Nicolas,

I'm using react-native-web and currently, I'm working on VideoPlayer component that uses ['react-native-video'](https://github.com/react-native-video/react-native-video/blob/master/Video.js#L5) library which uses 'resolveAssetSource' [function](https://reactnative.dev/docs/image#resolveassetsource).

I noticed that in react-native-web there is no export to the - resolveAssetSource function of Image from 'react-native'.

I noticed that there are a few issues with this but there is no solution.
Any suggestions?

Error:
```
`botstrap:83 Uncaught Error: Module parse failed: Unexpected token (19:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| const {pickScale} = require('./AssetUtils');
| 
> import type {ResolvedAssetSource} from './AssetSourceResolver';
| 
| let _customSourceTransformer, _serverURL, _scriptURL;
    at ../node_modules/react-native/Libraries/Image/resolveAssetSource.js (bootstrap:83:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./node_modules/react-native-video/Video.js (Video.js:5:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/screens/VideoScreen.tsx (VideoScreen.tsx:3:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/App.tsx (App.tsx:61:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./src/index.ts (index.ts:2:1)
    at __webpack_require__ (bootstrap:19:1)
.`
```

**Comment by necolas** [comment] 2023-04-16 16:26
Closing as a duplicate of https://github.com/necolas/react-native-web/issues/1666

**Closed by necolas** 2023-04-16 16:26 UTC
Labels: enhancement

**Comment by flyskywhy** [comment] 2023-07-24 09:20
@adids1221 , I resolved such problem like <https://github.com/react-native-video/react-native-video/blob/ce03223f94771153962285042f28bed8881d633c/Video.js#L5> in my APP, as described below.

My APP and <https://github.com/flyskywhy/GCanvasRNExamples> both use `react-app-rewired` instead of `react-scripts` to integrate `react-native-web` , so use <https://github.com/flyskywhy/GCanvasRNExamples> as an example here.

The solution is:

1. Add below
```
    config.resolve.alias[
      'react-native/Libraries/Image/resolveAssetSource'
    ] = path.resolve('web/aliases/react-native/resolveAssetSource.js');
```
into `GCanvasRNExamples/config-overrides.js`

2. Create `resolveAssetSource.js` into `GCanvasRNExamples/web/aliases/react-native/` with below content
```
// ref to https://github.com/necolas/react-native-web/issues/1666#issuecomment-656646041

export function resolveAssetSource(base64) {
  // strip tag png
  if (base64.indexOf('data:image/png;') >= 0) {
    base64 = base64.substring(base64.indexOf(',') + 1);

    const header = atob(base64.slice(0, 50)).slice(16, 24);
    const uint8 = Uint8Array.from(header, c => c.charCodeAt(0));
    const dataView = new DataView(uint8.buffer);

    return {
      width: dataView.getInt32(0),
      height: dataView.getInt32(4),
    };
  }

  // strip tag for jpeg
  if (base64.indexOf('data:image/jpeg;') >= 0) {
    base64 = base64.substring(base64.indexOf(',') + 1);

    let bindata = atob(base64);
    const data = Uint8Array.from(bindata, c => c.charCodeAt(0));

    var off = 0;
    while (off < data.length) {
      while (data[off] == 0xff) off++;
      var mrkr = data[off];
      off++;

      if (mrkr == 0xd8) continue; // SOI
      if (mrkr == 0xd9) break; // EOI
      if (0xd0 <= mrkr && mrkr <= 0xd7) continue;
      if (mrkr == 0x01) continue; // TEM

      var len = (data[off] << 8) | data[off + 1];
      off += 2;

      if (mrkr == 0xc0) {
        return {
          type: 'jpeg',
          bpc: data[off], // precission (bits per channel)
          width: (data[off + 1] << 8) | data[off + 2],
          height: (data[off + 3] << 8) | data[off + 4],
          cps: data[off + 5], // number of color components
        };
      }
      off += len - 2;
    }
  }
}
```
