### ISSUE TITLE
Touchable Opacity props warnings

### ISSUE THREAD

**Issue by dustinsavery** [necolas/react-native-web#261] opened 2016-11-23 20:59 UTC
I'm running into an issue where Touchable Opacity has additional props that React is throwing warnings on. I've verified in the code that those props exist on the latest version. Is there something I'm missing or should be doing?

Console: ```Warning: Unknown props `onStartShouldSetResponder`, `onResponderTerminationRequest`, `onResponderGrant`, `onResponderMove`, `onResponderRelease`, `onResponderTerminate` on <button> tag. Remove these props from the element.```

react-dom: 15.3.2
react-native-web: 0.0.51

**Comment by necolas** [comment] 2016-11-23 21:21
Are you installing React 15.4?

**Comment by dustinsavery** [comment] 2016-11-23 22:05
No, React and React-Dom are 15.3.2. Upgrading to 15.4 throws a ton of different errors.

**Comment by necolas** [comment] 2016-11-23 22:53
Can you share a bit more info about your setup or example code

**Comment by dustinsavery** [comment] 2016-11-23 22:55
```<TouchableOpacity
                  style={[ styles.cta, styles.primaryCta ]}
                  onClick={ () => this.goToLaunchLogin() }
                  onPress={ () => { this.goToLaunchLogin() } }>
...children...
</TouchableOpacity>```

Nothing out of the ordinary AFAIK. The warnings seem to be tied to https://github.com/necolas/react-native-web/blob/master/src/components/Touchable/TouchableOpacity.js#L186

**Comment by necolas** [comment] 2016-11-24 00:14
You'll only be seeing those warnings if the `ResponderEventPlugin` isn't installed. I can't reproduce the warnings in the examples, so I need a more information or a test case.

**Comment by dustinsavery** [comment] 2016-11-24 01:10
I haven't explicitly installed that. It appears that it's part of react/react-native, yeah?

**Comment by gethinwebster** [comment] 2016-11-24 14:26
I saw this same error when I accidentally ended up with `react@15.3.2` and `react-dom@15.4.1` installed together: fixed by downgrading to `react-dom@15.3.2`

**Comment by necolas** [comment] 2016-11-24 16:40
That makes sense. You shouldn't need to install `react-dom` yourself.

**Closed by necolas** 2016-11-24 16:40 UTC

**Comment by dustinsavery** [comment] 2016-11-28 19:19
That was it. `react-dom` was getting updated to `15.4.2` thanks to semvar. Thanks for the help!

**Comment by dorthwein** [comment] 2016-12-01 02:26
Just wanted to confirm that installing react-dom@15.3.2 resolves issue.

**Comment by dustinsavery** [comment] 2016-12-01 03:37
Confirmed, `15.3.2` for both `React` and `react-dom` fixes this issue.

**Comment by scottckr** [comment] 2019-02-18 12:50
This issue started popping up for me as well, running `react` and `react-dom` at `16.8.2` and `react-native-web` at `0.10.0`, seems to be tied to `FlatList`, any suggestions?
Basically the code: 
```
<View style={{ width: '100%', height: '100%' }}>
  <FlatList
    keyExtractor={item => item.id}
    data={rows}
    renderItem={(item) => <View/>}
  />
</View>
```
