### ISSUE TITLE
Clicking Touchable in some cases doesn't work

### ISSUE THREAD

**Issue by joaovieira23** [necolas/react-native-web#1962] opened 2021-03-25 12:33 UTC
**The problem**

The click is not recognized, this case occurs mainly in touchable laptops and notebooks, I did some tests with console.log () and debug and the click is not recognized.

![Gravação de tela de 25-03-2021 09_35_46](https://user-images.githubusercontent.com/45154356/112474005-cd391300-8d4d-11eb-9e99-57d7daa8b418.gif)

![Captura de tela de 2021-03-25 09-30-01](https://user-images.githubusercontent.com/45154356/112473123-b645f100-8d4c-11eb-88b2-6fc6b66a6f56.png)

**Reproduce**

https://codesandbox.io/s/elastic-almeida-rjqte
https://gyazo.com/2998eeda5ec88cb33ca4296b4ba092ab

Steps to reproduce:

1. Scroll down to see the buttons
2. Press the button
3. While the button is pressed down, move the pointer slightly
4. The button loses its pressed state even while the pointer is inside the button.

It is very similar to this issue, but this version has not been corrected: https://github.com/necolas/react-native-web/issues/1564

**Expected behavior**

What was expected is that it would recognize all clicks regardless of mouse, touchpad, that you triggered the onPress () method in all cases

Environment (include versions). Did this work in previous versions?

React Native for Web (version): 0.14.7
React (version): 16.9.0
Browser: All

**Comment by necolas** [comment] 2021-03-25 16:04
What are the steps to reproduce?
What should I be looking for in the demo?

**Comment by joaovieira23** [comment] 2021-03-25 16:55
> What are the steps to reproduce?
> What should I be looking for in the demo?

There are the steps

**Comment by necolas** [comment] 2021-03-25 18:54
Your sandbox is using 0.12. I can't reproduce the issue with 0.15

**Comment by necolas** [comment] 2021-03-26 18:01
Closing as I cannot reproduce this in 0.15

**Closed by necolas** 2021-03-26 18:01 UTC
