### ISSUE TITLE
styled-component from dependency causing css overrides

### ISSUE THREAD

**Issue by vishalnarkhede** [necolas/react-native-web#1586] opened 2020-04-12 06:56 UTC
@necolas  Hats off on the work of this library first of all!!

I am one the authors of [stream-chat-react-native](https://github.com/GetStream/stream-chat-react-native) sdk which is a chat component provider library. I want to make this library compatible with react-native-web. I have managed to make most of the changes, but last piece remaining is `styled-components`. And I just need some help regarding how to approach this issue.

So I am testing my changes in sample app (which has stream-chat-react-native as dependency)

- If I define a component `const X = styled(View)``;` on app level, and use it in app - everything works perfect
- If I define a component `const X = styled(View)``;` in my library (stream-chat-react-native), and use it in app -  component X gets rendered perfectly (with its original styles). But the styles defined on app level get overriden by dynamic css class `css-view-xxxxx`. So styles defined on app level get messedup for some reason.
- If I defined component `const X = <View>...</View>;` in my library (stream-chat-react-native), and use it in app - everything works great (basically without styled-components).

Its somewhat similar to - https://github.com/necolas/react-native-web/issues/1367

I can imagine, this is quite vague info for anyone to provide me solution. But can you please guide me regarding how should I approach the issue? Or maybe let me know if I can provide more info regarding this.

**Comment by vishalnarkhede** [comment] 2020-04-12 15:27
It only happens for locally linked package. So for now, my issue is resolved :)

**Comment by egislook** [comment] 2020-04-24 11:47
Yeah, I have the same issue. I'm using a bit different library but the core point is that the default CSS rules override the specified new styles

**Comment by egislook** [comment] 2020-04-27 11:08
So yeah it seems the issue is only happening when you link a library. Tho if you have a linked library inside your project you basically can not use Text or any `react-native` component because it gonna override the styling of the app with default component classes with identifier `CSS`. So, for now, it seems its better not to use a linked package or publish it and use it externally. I'll still gonna try to find the issue but it seems it creates a duplicate of the rule in the style.

**Comment by steida** [comment] 2020-04-27 15:34
I can't understand why anyone is using styled-components with RNW. It's a totally unnecessary and wrong abstraction.

**Comment by vishalnarkhede** [comment] 2020-04-28 06:08
@steida why do you think its a wrong abstraction? Point of `react-native-web` is to reuse react-native components for web apps.

**Comment by vishalnarkhede** [comment] 2020-04-28 06:13
@necolas any comments here? Am I doing something wrong?

**Comment by necolas** [comment] 2020-04-28 06:59
The issue isn't described clearly enough yet for me to understand what the problem is

**Comment by steida** [comment] 2020-04-28 19:06
@vishalnarkhede RNfW has it's own well-tailored and typed CSS-in-js. styled-components is an unnecessary abstraction on top of it.

**Comment by vishalnarkhede** [comment] 2020-04-29 09:17
@necolas I will try to setup an example repo with reproducible issue and get back to this :)

**Comment by necolas** [comment] 2020-04-30 19:44
Is it possible that you're running 2 different builds of RNW in the same app? For example if styled components is importing from the cjs build and the app is importing from the esm build

**Comment by necolas** [comment] 2020-05-27 23:18
Closing due to lack of actionable information

**Closed** 2020-05-27 23:18 UTC
