### ISSUE TITLE
PanResponder: missing properties in nativeEvent 

### ISSUE THREAD

**Issue by ttraenkler** [necolas/react-native-web#457] opened 2017-04-28 10:28 UTC
**What is the current behavior?**

The `PanResponder event.nativeEvent` is missing some documented properties: https://facebook.github.io/react-native/docs/panresponder.html

While additional properties to cover the mouse use case do not hurt, in particular it would be useful to have access to `locationX` and `locationY` for coordinates relative to the element.

Highlighted are the missing properties:
nativeEvent
**changedTouches** - Array of all touch events that have changed since the last event
**identifier** - The ID of the touch
**locationX** - The X position of the touch, relative to the element
**locationY** - The Y position of the touch, relative to the element
pageX - The X position of the touch, relative to the root element
pageY - The Y position of the touch, relative to the root element
target - The node id of the element receiving the touch event
timestamp - A time identifier for the touch, useful for velocity calculation
**touches** - Array of all current touches on the screen

Link to minimal test case: (template: [codepen](https://codepen.io/ttraenkler/pen/vmxxxe?editors=0011))

when dragging the output `"moving" undefined undefined` is logged

**What is the expected behaviour?**

logging `"moving" 23 56` for example if the mouse position is x=23 y=56 relative to the element origin

**Steps to reproduce**

1. open playground
2. drag with the mouse anywhere in the view
3. see console output

**Environment (include versions)**

OS: MacOS 10.12.4
Device: Macbook Pro
Browser: Google Chrome 57.0.2987.133
React Native for Web (version): latest
React (version): 15.3.1

**Comment by necolas** [comment] 2017-04-28 22:01
Thanks for reporting this. Interested, I would have expected it to work as the events coming out of View are normalized. Since Twitter isn't using the `PanResponder` yet and this issue isn't blocking me from rendering Twitter Lite with RNW, I probably won't get to this in the short term. If you're interested in investigating further to help me identify the root issue, that would be a great help.

Related #171

**Comment by ttraenkler** [comment] 2017-04-28 23:14
Thanks for your feedback. I will need work around the issue one way or another, so with your guidance I could help tracking down this issue in react-native-web. I need to know more about the internals of the event normalization. Where is this done in react or react-native-web?

**Comment by ttraenkler** [comment] 2017-04-29 00:12
Note I also noticed that `onResponderMove` fires also if the mouse is just moved through a pan responder view without pressing any mouse button.

**Comment by necolas** [comment] 2017-04-29 19:07
Event transform takes place here: https://github.com/necolas/react-native-web/blob/master/src/modules/createDOMElement/index.js

> Note I also noticed that onResponderMove fires also if the mouse is just moved through a pan responder view without pressing any mouse button.

I can't reproduce that when running the examples locally, and made specific changes (a long time ago) to prevent that from happening.

**Comment by ttraenkler** [comment] 2017-05-03 15:31
In order to reproduce `onResponderMove` firing with no mouse button pressed I've added `onMoveShouldSetPanResponder: () => true,` to the above codepen example - now after the initial mouse button press, even after releasing the button, whenever the mouse enters the view the `onResponderMove` events keep firing.

**Comment by ttraenkler** [comment] 2017-05-03 16:14
I've run the `PanResponderExample.js` in the react-native-web examples and added some debug outputs to the functions called in the event normalization. Turns out when the `createDOMElement` function in `createDOMElement/index.js` is called, the inner arrow function in the nested arrow functions of `wrapEventHandler` it seems is never called - I have simply added a console.log after line 34 which is never printed, while createDOMElement is called several times. I'll see if I can give more specific info later.

**Comment by RangerMauve** [comment] 2017-05-08 21:39
@ttraenkler Did you have any workarounds for the issue with `onMoveShouldSetPanResponder` making `onResponderMove` fire even without a press?

**Comment by RangerMauve** [comment] 2017-05-08 22:19
Disregard my comment, setting it to `false` for move events and just having `true` for clicks solved my issues.

**Comment by code-by** [comment] 2017-05-25 17:47
@RangerMauve could you provide example, please?

**Comment by ttraenkler** [comment] 2017-05-25 17:55
@code-by onMoveShouldSetPanResponder: () => false in my pen should do the trick

**Comment by RangerMauve** [comment] 2017-05-25 18:24
I've actually ditched the PanResponder for our particular use-case because performance was abysmal on mobile devices with Cordova. Though that may have been a result of us doing things wrong.

**Comment by code-by** [comment] 2017-05-25 20:20
Is there solution for PanResponder works only when left mouse buttons is pressed?

**Comment by RangerMauve** [comment] 2017-05-25 20:21
@code-by Is the problem that you want the right button to work as well?

**Comment by necolas** [comment] 2017-06-09 17:57
In terms of `nativeEvent` object, that should now be fixed in 0.0.98 and above.

**Closed by necolas** 2017-06-09 17:57 UTC
Labels: bug
