### ISSUE TITLE
PanResponder locationX Y coordinates incorrect for views with children

### ISSUE THREAD

**Issue by jacobp100** [necolas/react-native-web#1333] opened 2019-04-26 09:08 UTC
**The problem**

A view with children a pan responder will have the locationX and Y values of the move event relative to its children view

**How to reproduce**

Simplified test case: https://codesandbox.io/s/2x4q5knqzr

Steps to reproduce:

1. Create a view with a pan responder
2. Add children at a non-origin position in the view
3. Tap and move on the parent view
4. Observe the locationX and Y coordinates are correct
5. While keeping your finger pressed, move over the child view
6. The locationX and Y coordinates are relative to the child view

**Expected behavior**

6. The locationX and Y coordinates are relative to the view where the pan responder was attached

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): TBC
* React (version): TBC
* Browser: Chrome, Safari (latest)

**Comment by necolas** [comment] 2019-04-26 14:13
Duplicate of #693

**Closed by necolas** 2019-04-26 14:13 UTC
