### ISSUE TITLE
Touchable: odd touch target when using transform styles

### ISSUE THREAD

**Issue by starkyru** [necolas/react-native-web#894] opened 2018-04-13 07:48 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
https://aboard-wildflower.glitch.me

1. Everything works fine if Touchable or it's parent positioned absolutely.
2. When a parent has transformed position in style - it becomes unhighlighted and fails to register click after mouse down and mouse movement after that.
3. Same issue with an absolutely positioned child of Touchable.

**What is the expected behavior?**
Touchable registers all clicks.

**Environment (include versions). Did this work in previous versions?**
rn-web: 0.1.?, 0.5.1, 0.5.4 - same behavior. 

* OS: MacOS
* Browser: Chrome, Safari
* React Native for Web (version): 0.5.4
* React (version): 0.16.2

**Comment by necolas** [comment] 2018-04-15 22:48
Your example looks like it has problems behaving as you're expecting in React Native too.

**Comment by necolas** [comment] 2018-04-18 20:12
I think this is because React Native's layout/measure doesn't account for transforms

**Comment by necolas** [comment] 2018-12-31 16:11
Closing as a duplicate of #1151

**Closed by necolas** 2018-12-31 16:11 UTC
