### ISSUE TITLE
Image onLoad event, the event target/currenttarget properties are null

### ISSUE THREAD

**Issue by sbin1211** [necolas/react-native-web#2486] opened 2023-02-15 11:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

on chrome Version 109.0.5414.119 (Official Build) (x86_64)
when pass onLoad event to Image, then call
const { target } = event.nativeEvent;

the target is null.

as you wrap the onLoad event of ImageLoader on settimeout.

```
  load(uri: string, onLoad: Function, onError: Function): number {
    id += 1;
    const image = new window.Image();
    image.onerror = onError;
    image.onload = (e) => {
      // avoid blocking the main thread
      const onDecode = () => onLoad({ nativeEvent: e });
      if (typeof image.decode === 'function') {
        // Safari currently throws exceptions when decoding svgs.
        // We want to catch that error and allow the load handler
        // to be forwarded to the onLoad handler in this case
        image.decode().then(onDecode, onDecode);
      } else {
        setTimeout(onDecode, 0);
      }
    };
    image.src = uri;
    requests[`${id}`] = image;
    return id;
  },
  
  ```

instead, i think you need update the code like this

```
  load(uri: string, onLoad: Function, onError: Function): number {
    id += 1;
    const image = new window.Image();
    image.onerror = onError;
    image.onload = (e) => {
      // avoid blocking the main thread
      
    ---->  const cloneEvent={};
      cloneEvent.target=e.target;
      ... other orginal event properties.
      
      const onDecode = () => onLoad({ nativeEvent: cloneEvent });
      if (typeof image.decode === 'function') {
        // Safari currently throws exceptions when decoding svgs.
        // We want to catch that error and allow the load handler
        // to be forwarded to the onLoad handler in this case
        image.decode().then(onDecode, onDecode);
      } else {
        setTimeout(onDecode, 0);
      }
    };
    image.src = uri;
    requests[`${id}`] = image;
    return id;
  },
  
  ```

### Expected behavior

the target is NOT null

### Steps to reproduce

call bellow code, the target is null.

```
	<Image
		onLoad={(event) => {
			const { target } = event.nativeEvent;
			console.log(target);
		}}
		source={{
			uri: 'https://media.istockphoto.com/id/1156404289/vector/free-3d-speech-bubble-sign.jpg?s=612x612&w=0&k=20&c=my4PkXf-u4HHoW_xGpkQuMHRB8yBQswQ8Xw8U7sakHg=',
		}}
	/>;
			
```

### Test case

none

**Comment by sbin1211** [comment] 2023-02-15 11:39
look at this article
https://stackoverflow.com/questions/67790001/event-listener-target-is-null-after-delay-with-set-time-out

**Comment by kidroca** [comment] 2023-02-15 18:58
The `setTimeout` is only used when `if (typeof image.decode === 'function')` 

This is a feature check from the time where `image.decode` was not available in every browser

I think this still might be down to the `decode` function taking some (async) time before calling `onDecode` 

In the end I don't think we should expose the `target` as you propose, because 
1. It doesn't match the react native image interface for the `onLoad` event: https://reactnative.dev/docs/image#imageloadevent
2. The image here is not the element rendered in the react dom 

If a `target` should be exposed IMO it should be the `<img>` rendered in the react dom 

---

What's the use case you have to need a `target` from the onLoad event?
I think you can just use a ref to get it, e.g. 

```jsx
const imgRef = React.useRef();

return <Image ref={imgRef} />;
```

**Comment by necolas** [comment] 2023-02-15 19:55
Closing as duplicate of #2469

**Closed by necolas** 2023-02-15 19:55 UTC
Labels: bug
