### ISSUE TITLE
web tab navigator doesnt change of menu

### ISSUE THREAD

**Issue by omaraga12** [necolas/react-native-web#2444] opened 2022-11-27 04:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Hello, my app was working good on web one moth ago, however I got an error when I am tryng to change to other menu the screen shows correctly, but when I try to touh I fell that I am still in the before screen, You can see more detail in this video:

https://user-images.githubusercontent.com/64969223/204119382-9eba38b7-e074-4601-8c6b-8d2822c91afb.mp4

### Expected behavior

Coul navigate on the other screen

### Steps to reproduce

1. I change of screen
2. The screen changes good
3. When I touch looks like I am touching the before screen

### Test case

I

**Comment by necolas** [comment] 2022-11-28 19:25
This might be a bug in your navigation code. No way for me to tell from a video of an app being used. Closing because there's no reproducible test case related to the code maintained in this repo.

**Closed by necolas** 2022-11-28 19:25 UTC
Labels: bug, needs: issue template
