### ISSUE TITLE
Webpack issues in multi-platform app

### ISSUE THREAD

**Issue by cobarx** [necolas/react-native-web#1117] opened 2018-09-25 21:44 UTC
**The problem**
When attempting to use the standard function properties in a component like `render()` and `componentDidMount()`, I'm getting errors for those functions not being defined:

```Warning: Test(...): No `render` method found on the returned component instance: you may have forgotten to define `render`.```

and

```Uncaught TypeError: instance.render is not a function```

I'm also not able to set breakpoints in the Chrome or Firefox JS Debugger. I can only set them for the first line. See here:
![no breakpoints](https://user-images.githubusercontent.com/4063255/46044909-f4f18680-c0d0-11e8-8b21-19f0da68f734.jpg)

**How to reproduce**
I've setup a new React Native project and added react-native-web following the Multi Platform App guide including using the webpack.config.js file from the guide.

Simplified test case: 
```
import React, { Component } from "react";

export default class Test extends Component {
    // throws error
    render() {
        return null;
    }

    // works properly
    render = () => {
        return null;
    }
}
```

package.json:
```
{
  "name": "vilos",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest",
    "web-dev": "webpack-dev-server -d --config web/webpack.config.js --inline --hot --colors",
    "build": "webpack -p --config ./web/webpack.config.js"
  },
  "dependencies": {
    "@babel/runtime": "^7.0.0",
    "prop-types": "^15.6.2",
    "react": "16.5.0",
    "react-art": "^16.5.2",
    "react-dom": "^16.5.2",
    "react-native": "0.57.1",
    "react-native-video": "^3.2.1",
    "react-native-web": "^0.9.0",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-act": "^1.7.4",
    "redux-logger": "^3.0.6"
  },
  "devDependencies": {
    "babel-jest": "23.6.0",
    "babel-loader": "^8.0.2",
    "babel-plugin-react-native-web": "^0.9.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react-native": "5.0.2",
    "jest": "23.6.0",
    "metro-react-native-babel-preset": "0.46.0",
    "react-test-renderer": "16.5.0",
    "url-loader": "^1.1.1",
    "webpack": "^4.19.1",
    "webpack-cli": "^3.1.1",
    "webpack-dev-server": "^3.1.9"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Expected behavior**
I should be able to declare `render() { /* some code */ }` without errors.

It should be possible to set breakpoints on any line in the debugger where code evaluation is being done.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.9.0
* React (version): 16.5.0
* React Native (version): 0.57.1
* Browser: Chrome & Firefox

**Comment by necolas** [comment] 2018-09-25 23:37
Have you enabled webpack source maps? The example configuration I provided isn't going to cover every case. You'll have to look at the webpack docs for more. I don't know what could be the problem with `render`, etc. It might be that your babel configuration isn't right. It's not an issue with the RNW library itself so I'm going to close this. But please let me know if you find the cause is related to the example webpack configuration I provided. Thanks :)

**Closed by necolas** 2018-09-25 23:37 UTC

**Comment by niksosf** [comment] 2018-11-30 05:45
@cobarx thanks for providing the working scenario `render = () => {}`, I think for my case it may be because of the babel plugin `class properties` { "plugins" : [    "@babel/plugin-proposal-class-properties",]}`
