### ISSUE TITLE
global style pollution

### ISSUE THREAD

**Issue by Maolh** [necolas/react-native-web#2036] opened 2021-06-01 06:39 UTC
The Problem
We tried to use the React-Native-Web packaging component library. To implement on-demand introduction, we packaged each component separately. But because the style handling is CSSStylesheet, it causes global style pollution.

How to reproduce
We developed a set of component libraries using RN. We wanted to package each component into a JS through React-Native-Web, and refer to the components in the host project according to their own needs.
![image](https://user-images.githubusercontent.com/38041292/120417285-2dbd7f80-c391-11eb-9029-0a7038d9e2e0.png)
We can see from the usage that since the id of CSSStylesheet is fixed and it is all 'react-native-stylesheet', the globally unique CSSStylesheet will be accumulated backwards when it is introduced on demand. Also, CSSStyleRule names can be duplicated, which can lead to style overlay and other issues, resulting in a global style pollution
![image](https://user-images.githubusercontent.com/38041292/120417312-37df7e00-c391-11eb-9797-7f1f01ed2f8a.png)
![image](https://user-images.githubusercontent.com/38041292/120417326-3c0b9b80-c391-11eb-8674-9a15f82fb384.png)
![image](https://user-images.githubusercontent.com/38041292/120417446-69584980-c391-11eb-8f9c-2f0765bc1106.png)

Environment
react-native-web: 0.14.13
react:  ^16.5.1
browser : 
Google Chrome
版本 90.0.4430.212（正式版本） (x86_64)

**Comment by Maolh** [comment] 2021-06-02 03:35
The question has been reedited

**Comment by necolas** [comment] 2021-06-02 04:33
The styles will be duplicated if you have 2 different versions of react native for web running on the client, including if you bundled both the es and cjs module formats in your app. I don't know how you got font face rules in the style sheet when the framework doesn't support those. You shouldn't be writing styles to the framework's style sheet.

I'm going to close this for now because there is still no steps to reproduce an issue, no test case to show it, and not enough information provided to take this any further.

**Closed by necolas** 2021-06-02 04:33 UTC
Labels: needs: issue template

**Comment by Maolh** [comment] 2021-06-02 04:46
I didn't write the style into the framework's stylesheet, it was all converted through React - Native - Web. The RN component library contains many components, each of which is packaged into a separate JS because the framework internally has fixed CSSStylesheet to a style with an ID named React -Native Stylesheet. So if I use style in a host project, I'm going to be operating in the same stylesheet, and I'm going to have duplicate names, and I'm going to overwrite them, and I'm going to have style chaos

**Comment by necolas** [comment] 2021-06-02 08:48
The StyleSheet doesn't insert rules if they already exist. You probably have a bug in your code
