### ISSUE TITLE
When exporting components as a package I get "getDefaultProps" warnings (web)

### ISSUE THREAD

**Issue by liron-navon** [necolas/react-native-web#1285] opened 2019-03-12 13:42 UTC
**Is your feature request related to a problem? Please describe.**
I'm building a component library to be shared across multiple projects, I wish to export components as a package, but when I do, I get warnings in the console, If I don't export them and just use RNW directly I don't get those warnings, can you please help me? I guess I'm missing something here...

**Describe a solution you'd like**
Be able to export components without those annoying warnings.

**Additional context**
Since this is not ready at all, I didn't publish it to npm, but it's easy to setup and test:

1. setup the project and a react cra app:
```
# create the projects
git clone git@github.com:liron-navon/react-native-web-components-boilerplate.git my-components
npx create-react-app my-app

# setup the components library to be consumed as an npm package
cd my-components
npm install
npm link

# setup the app to use the package and RNW
cd my-app
npm install --save react-native-web react-art
npm link my-components
```

2. And add the components anywhere, for example `App.js` can be changed to:
```
import React, { Component } from 'react';
import './App.css';
import 'react-native';
import {Button} from 'my-components';
class App extends Component {
  render() {
    return (
        <Button
            color={'red'}
            accessibilityLabel={"button"}
            onPress={() => console.log('onPress')}
            title="Button"
        />
    );
  }
}
export default App;
```

3. start the react cra app
```
npm start
```

4. This works great, but check the console, we get this error:
```
Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.
```

The call stack (only leads to react/react-dom):
```
function.console.(anonymous function) | @ | index.js:1446
-- | -- | --
  | warningWithoutStack | @ | react.development.js:188
  | validatePropTypes | @ | react.development.js:1724
  | createElementWithValidation | @ | react.development.js:1809
  | r.render | @ | index.js:4688
  | finishClassComponent | @ | react-dom.development.js:15276
  | updateClassComponent | @ | react-dom.development.js:15231
  | beginWork | @ | react-dom.development.js:16221
  | performUnitOfWork | @ | react-dom.development.js:20241
  | workLoop | @ | react-dom.development.js:20282
  | renderRoot | @ | react-dom.development.js:20362
  | performWorkOnRoot | @ | react-dom.development.js:21319
  | performWork | @ | react-dom.development.js:21229
  | performSyncWork | @ | react-dom.development.js:21203
  | requestWork | @ | react-dom.development.js:21058
  | scheduleWork | @ | react-dom.development.js:20871
  | scheduleRootUpdate | @ | react-dom.development.js:21566
  | updateContainerAtExpirationTime | @ | react-dom.development.js:21592
  | updateContainer | @ | react-dom.development.js:21660
  | push../node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render | @ | react-dom.development.js:21973
  | (anonymous) | @ | react-dom.development.js:22125
  | unbatchedUpdates | @ | react-dom.development.js:21448
  | legacyRenderSubtreeIntoContainer | @ | react-dom.development.js:22121
  | render | @ | react-dom.development.js:22196
  | ./src/index.js | @ | index.js:7
  | __webpack_require__ | @ | bootstrap:781
  | fn | @ | bootstrap:149
  | 0 | @ | serviceWorker.js:135
  | __webpack_require__ | @ | bootstrap:781
  | checkDeferredModules | @ | bootstrap:45
  | webpackJsonpCallback | @ | bootstrap:32
  | (anonymous) | @ | main.chunk.js:1
```

**Comment by necolas** [comment] 2019-03-12 17:08
This search shows that `getDefaultProps` is only used in a few React Native components that still use `createClass`: https://github.com/necolas/react-native-web/search?q=getDefaultProps&unscoped_q=getDefaultProps

I can't reproduce this problem locally and no one else developing component libraries has reported a similar issue, so I'm going to close this until there is a reproducible example that points to a problem in RNW.

**Closed by necolas** 2019-03-12 17:08 UTC

**Comment by liron-navon** [comment] 2019-03-14 12:53
` no one else developing component libraries ` Do you have an example for a component library built with RNW so I can check how they set it up?

**Comment by soundyogi** [comment] 2019-04-07 13:10
I have the same Problem.

I am trying to SSR a Nextjs app.  

Without the plugin, the first SSR pass is missing styles.
With the plugin I get 'getDefaultProps' warnings.
Somehow they are introduced into the component lib. When I build the lib without the babel-plugin the 'getDefaultProps' strings are gone from the dist build.

**Comment by soundyogi** [comment] 2019-04-09 10:01
So I solved it in the following way:

DO NOT use the babel-plugin when building the component-lib, it will introduce getDefaultProps (it did for me)

DO use the babel-plugin in your next/production build.

Now I dont have FOUC anymore, and no warngings :)
