### ISSUE TITLE
textarea auto height

### ISSUE THREAD

**Issue by lxjwlt** [necolas/react-native-web#1083] opened 2018-08-26 13:55 UTC
**Is your feature request related to a problem? Please describe.**
TextInput is rendered to `textarea`, multiline text would make it to show scrollbar, expect TextInput to adjust its height to fit text, like the same way in native app

**Describe a solution you'd like**
maybe [autosize](https://github.com/jackmoore/autosize) or [editable](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content) could help

**Describe alternatives you've considered**

**Additional context**

**Comment by necolas** [comment] 2018-08-30 15:15
Duplicate of https://github.com/necolas/react-native-web/issues/795

**Closed by necolas** 2018-08-30 15:15 UTC
