### ISSUE TITLE
What version of react-native is supported?

### ISSUE THREAD

**Issue by zhangking** [necolas/react-native-web#532] opened 2017-06-20 06:25 UTC

**Comment by damiaozi** [comment] 2017-06-20 08:45
i use 0.39.2

**Comment by RyanThomas73** [comment] 2017-06-21 05:41
**'react-native' version:** 0.42.3

From v0.43.0+ react-native has a react peer dependency of `16.0.0-alpha.X` and react-native-web won't currently work with the 16.0 versions of react.

**Comment by necolas** [comment] 2017-06-29 18:12
Closing as a duplicate of a task in #491

**Closed by necolas** 2017-06-29 18:12 UTC
