### ISSUE TITLE
How to turn off spell check in TextInput?

### ISSUE THREAD

**Issue by code-by** [necolas/react-native-web#501] opened 2017-06-01 15:12 UTC
Hello!
I'd like to turn off spell checking in TextInput.
It is possible?
Screenshot from Google Chrome latest version.
![screen-2017-05-31_13-54-18_](https://cloud.githubusercontent.com/assets/4306445/26686508/21ca2f36-46bb-11e7-9d0d-8c7b082742bd.jpg)

**Comment by necolas** [comment] 2017-06-01 15:16
I couldn't reproduce this. What is the code? What OS? What versions of the libraries?

https://github.com/necolas/react-native-web/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by necolas** [comment] 2017-06-06 14:54
Closing until there is enough info to track down a problem. Thanks

**Closed by necolas** 2017-06-06 14:54 UTC
Labels: needs more information

**Comment by alexandergunnarson** [comment] 2018-01-31 04:39
I, too, can't turn off spell checking in `TextInput`. I'm doing `spellCheck: false` but to no avail. According to the [HTML5 spec](https://html.spec.whatwg.org/multipage/interaction.html#spelling-and-grammar-checking), the correct DOM property is `spellcheck` (no caps). This is confirmed by manually editing the element in the inspector in the latest version of Chrome. No guarantees as to browser compatibility ([this StackOverflow article](https://stackoverflow.com/questions/254712/disable-spell-checking-on-html-textfields) claims that it doesn't work on iOS Safari, though `autocorrect=false` does at least), but it's something to consider adding.

**Comment by necolas** [comment] 2018-01-31 18:33
Should be working in 0.3.4

**Comment by alexandergunnarson** [comment] 2018-02-01 14:21
Awesome, thanks so much!

**Comment by alexandergunnarson** [comment] 2018-02-01 14:29
Disclaimer: it appears I was using version 0.2.2 previously which had slipped past me... but when I looked through the `react-native-web` code on master yesterday it had still looked like the hookup I was talking about wasn't working. So all in all I think your efforts were not in vain! Thanks again!
