### ISSUE TITLE
Inconsistencies between react-native and react-native-web

### ISSUE THREAD

**Issue by bmcmahen** [necolas/react-native-web#166] opened 2016-07-12 21:47 UTC
Just some inconsistencies between react-native and react-native-web that I've noticed while building the panza ui explorer (found [here](https://github.com/bmcmahen/panza-ui-explorer). You can see the active branch for panza [here](https://github.com/bmcmahen/panza/tree/docs). We are hoping to have basic `react-native-web` support in the next major release. 

## TextInput 
- By default, TextInput on react-native does not have a `border`, `width`, or `height`. The `border` in `react-native-web` can't seem to be removed. I've tried settings `borderWidth: 0` and `borderColor: transparent` to the styles, but it doesn't seem to help.

##  View: 

- React-native tends to stretch the component to the full width when react-native-web does not. In particular, when rendering a ListView item using [TouchableRow](https://github.com/bmcmahen/panza/blob/docs/src/Row/TouchableRow.js) I need to set the`TouchableRow` to have a `{width: 100%}` to get it to span the full container width. On iOS, I don't need to do this. 

So far these seem to be the two biggest issues I've encountered, with Input styling being the most difficult. I'll update as I encounter more issues. Some of these might also be caused by my lack of familiarity with flexbox, too.

**Comment by necolas** [comment] 2016-07-13 00:02
Is there a reduced test case for the View issue? Hard to tell what is going on from looking at the component you linked to.

**Comment by necolas** [comment] 2016-07-13 00:29
I can reproduce the `TextInput` issue (which only manifests when using `StyleSheet.create`):
http://codepen.io/necolas/pen/BzmYkA?editors=0010

> By default, TextInput on react-native does not have a border, width, or height.

This only seems to be true for iOS. Android has renders an underline and doesn't seem to support setting a border at all. Not having a default height is crazy though and not something I think a web version should emulate.

**Comment by necolas** [comment] 2016-07-13 00:48
The `TextInput` issue you identified should be fixed in 0.0.37.

**Comment by bmcmahen** [comment] 2016-07-13 01:23
I'll try to recreate the `View` issue in a reduced test case. It might have to wait a few days though.

**Comment by necolas** [comment] 2016-07-13 02:13
OK, for now do you have a link to the code you're running when you see this issue?

**Comment by bmcmahen** [comment] 2016-07-13 02:49
The example repo that I'm working with is [bmcmahen/panza-ui-explorer](https://github.com/bmcmahen/panza-ui-explorer). And [this](https://github.com/bmcmahen/panza-ui-explorer/blob/master/components/ExampleList.js#L43) is the code that renders the example list items, which initially weren't spanning the full width on the web until I set `{width: 100%}` on [TouchableRowCell](https://github.com/bmcmahen/panza/blob/docs/src/Row/TouchableRowCell.js#L90).

**Comment by necolas** [comment] 2016-07-13 03:21
Thanks (I should have re-read your initial post). Turns out the `ListView` PR I merged is using `divs` - https://github.com/necolas/react-native-web/blob/f8c4cdb93693faba7b0fde9c0754ab20d491728b/src/components/ListView/index.js#L67 - which means the flexbox layout is interrupted and explains the issue you've reported.

**Comment by necolas** [comment] 2016-07-13 04:21
These issues should be fixed in 0.0.38. Thanks for reporting them.

**Closed** 2016-07-13 04:20 UTC

**Comment by bmcmahen** [comment] 2016-07-13 07:52
Thanks @necolas. I appreciate the good work & I'll report more issues if I come across any.
