### ISSUE TITLE
TouchableOpacity triggering <input> and <TextInput>

### ISSUE THREAD

**Issue by bcpugh** [necolas/react-native-web#1164] opened 2018-11-05 16:47 UTC
**The problem**
On safari mobile, TouchableOpacity will trigger another component at the same location when changing views (if second component is an `"<input>"` or `"<TextInput>"`). 

`<input>` example provided below. Similar behavior for a TextInput at same location; however, unable to reproduce succinctly in sandbox (using Redux Form for this implementation).

**How to reproduce**
https://codesandbox.io/s/6njwzqojnr
(I tried to minimize redux / router code).
If you load on mobile safari on iPhone and click the upper left of the first component (i.e.TouchableOpacity, blue) it will trigger the second component (i.e. `<input>`, red).

Steps to reproduce:
1. TouchableOpacity overlapping where <input> in second view, w/ onPress triggers view change
2. User touches TouchableOpacity in the overlapping location
3. <input> gets triggered unintentionally. Longer presses increase frequency of unexpected behavior

**Expected behavior**
Expected touchstart and touchend events only.
(Using safari devtools hooked up to my iPhone, recorded events are: touchstart, touchend, mouseover, mousemove, mousedown, mouseup, and click (<-- targets the input file).  In my app, the final click gets fired twice, even.

RNW: 0.9.6
RN: 0.57.4
Browser: Safari (iOS12, iPhone 7)

**Comment by hushicai** [comment] 2018-11-15 06:07
i think this is caused by `mouse` event,  even though the  emulated mouse events filter time is now 1000ms from c3cbd53a8a32367a16f7cdfde264ddcd40d95876, it is still happen sometimes in some browser and some specific case.

my solution is to disable `mouse` event if  in touch screen.

```js
if ('ontouchstart' in window) {
  let stop = e => {
    return e.stopPropagation();
  };

  document.body.addEventListener('mousemove', stop, true);
  document.body.addEventListener('mousedown', stop, true);
  document.body.addEventListener('mouseup', stop, true);
}
```

`mouse` event make no sense in mobile.

and if app is runnning in pc, `mouse` event will not be disabled because of `'ontouchstart' in window`.

**Comment by necolas** [comment] 2018-11-15 06:14
There are PC with touch screen so the single window check is not safe

**Comment by hushicai** [comment] 2018-11-15 06:20
ok, but it works indeed.

the problem is that `touch` and `mouse` happened together.

if touch is supported on a device, then ignore mouse event; otherwise, use mouse event.

**Comment by necolas** [comment] 2019-01-03 21:23
Closing this issue so we can coordinate findings and solutions in #1219

**Closed by necolas** 2019-01-03 21:23 UTC
