### ISSUE TITLE
<Text> with properties numberOfLines & ellipsizeMode

### ISSUE THREAD

**Issue by soyjavi** [necolas/react-native-web#814] opened 2018-02-13 06:35 UTC
**Do you want to request a *feature* or report a *bug*?**
It's a bug

**What is the current behavior?**
If you use `numberOfLines` with a number > 1 the property `ellipsizeMode` doesn't work. 

**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar (template:
https://glitch.com/edit/#!/react-native-web-playground).**

1. Use  `<Text numberOfLines={1} ellipsizeMode="tail" />` WORKS
2. Use `<Text numberOfLines={2} ellipsizeMode="tail" />` DOESN'T WORK

**What is the expected behavior?**
The rule `ellipsizeMode` must be applied.

**Comment by necolas** [comment] 2018-02-13 06:50
Duplicate of #13

**Closed by necolas** 2018-02-13 06:50 UTC
