### ISSUE TITLE
Content get squashed when keyboard open

### ISSUE THREAD

**Issue by minuitagency** [necolas/react-native-web#2099] opened 2021-07-28 14:28 UTC
**The problem**
When we try to focus on a field and open the keyboard, the whole content get distorted.

**How to reproduce**
As soon as we open a field, the layout is resized.

![05f921b8-18de-4b08-85f6-a83a1c6458bb](https://user-images.githubusercontent.com/38316888/127340117-c65815b4-0aa9-4e73-905e-209e00055753.jpg)
![538c1d9d-fd1c-40e4-899a-8739527f5b10](https://user-images.githubusercontent.com/38316888/127340130-dd40ede5-f6a0-4342-b7b6-94594d0164d2.jpg)

**Expected behavior**
The layout should not move.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.11.7
* React (version): 16.9.0
* Browser: Chrome android

**Comment by necolas** [comment] 2021-07-28 18:24
I'm going to close this because you're using a very old version of RNfWeb, and have not provided an actionable test case to reproduce an issue.

**Closed by necolas** 2021-07-28 18:24 UTC
Labels: needs: issue template
