### ISSUE TITLE
ImageBackground

### ISSUE THREAD

**Issue by rmevans9** [necolas/react-native-web#686] opened 2017-10-18 17:19 UTC
**Do you want to request a *feature* or report a *bug*?** Feature

**What is the current behavior?** 

ImageBackground provided by React Native is unavailable in React Native Web

**What is the expected behavior?**

Alias ImageBackground to Image since the functionality didn't really change as far as I can tell. This would allow for us to use ImageBackground on React Native and not have it blow up in Web

**Comment by rmevans9** [comment] 2017-10-18 17:19
I can work on making a PR if the direction of making it redirect to Image works for everyone.

**Comment by necolas** [comment] 2017-10-18 17:34
Thanks. This is a duplicate of what is listed in the #91 component backlog. The necessary implementation is as in react-native.

**Closed by necolas** 2017-10-18 17:34 UTC
