### ISSUE TITLE
React Navigation Support

### ISSUE THREAD

**Issue by zhaoxy2850** [necolas/react-native-web#626] opened 2017-09-11 14:40 UTC
Hi guys, I'm trying to use react-native-web to build my app for ios, android and web. But I'm stuck at how to use react-navigator(http://facebook.github.io/react-native/docs/navigation.html#react-navigation) in the react-native-web. Any ideas?
Thanks.

**Comment by rmevans9** [comment] 2017-09-11 16:01
What part is giving you difficulty? I am using `react-navigation` with `react-native-web` successfully right now.

**Comment by necolas** [comment] 2017-09-11 17:29
You might find some answers in closed issues or stackoverflow. Closing as this is not a bug or feature request

**Closed by necolas** 2017-09-11 17:29 UTC

**Comment by zeitamin** [comment] 2019-02-16 15:56
> What part is giving you difficulty? I am using `react-navigation` with `react-native-web` successfully right now.

which version do you use?

**Comment by zhaoxy2850** [comment] 2019-02-17 05:44
Sorry, it was my own problem and it was solved. Thank you. :)
