### ISSUE TITLE
Animated.Value is not a constructor

### ISSUE THREAD

**Issue by efoken** [necolas/react-native-web#2487] opened 2023-02-15 19:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I'm trying the new RNW canary and getting this error in Storybook when I try to use `Animated.Value`:

```
Uncaught TypeError: react_native__WEBPACK_IMPORTED_MODULE_2__.default.Value is not a constructor
```

`console.log(Animated)` prints the following:

```
{FlatList: {…}, Image: {…}, ScrollView: {…}, SectionList: {…}, Text: {…}, …}
FlatList: {$$typeof: Symbol(react.forward_ref), render: ƒ}
Image: {$$typeof: Symbol(react.forward_ref), render: ƒ}
ScrollView: {$$typeof: Symbol(react.forward_ref), render: ƒ}
SectionList: {$$typeof: Symbol(react.forward_ref), render: ƒ}
Text: {$$typeof: Symbol(react.forward_ref), render: ƒ}
View: {$$typeof: Symbol(react.forward_ref), render: ƒ}
default: {Value: ƒ, ValueXY: ƒ, Color: ƒ, Interpolation: ƒ, Node: ƒ, …}
[[Prototype]]: Object
```

So `Animated.default.Value` seems to work 😅 I don't know if this error is only Storybook related... I got this issue after updating from RNW 0.18.0 to canary

### Expected behavior

`Animated.Value` should work without problems.

### Steps to reproduce

Use following code:

```jsx
import { Animated } from 'react-native';

// ...

new Animated.Value(0)
```

### Test case

https://codesandbox.io/p/sandbox/thirsty-swirles-txtwfs

**Comment by efoken** [comment] 2023-02-15 22:50
@necolas I will setup a template, but in the meantime I checked what has changed in Animated and here’s the problem: https://github.com/necolas/react-native-web/commit/a5de15dc3ad3e0ec333605ac9f67a9f62b9135a1#diff-142d66f7958d297392cbcf247a4f334077e0fd4cf74e70b22aa94997131942ddR26

**Comment by efoken** [comment] 2023-02-16 08:36
Test cases added

**Comment by efoken** [comment] 2023-02-18 15:33
@necolas I found out that Jest is running without any problem (using babel-jest) with the same babel.config.js that Storybook uses. The thing is that Storybook uses the module and Jest uses the CJS bundle ... will try to add this to my test case.

**Comment by necolas** [comment] 2023-02-18 21:34
Thanks for finding the cause, I will patch this soon

**Comment by necolas** [comment] 2023-03-27 17:31
Fixed in master

**Closed by necolas** 2023-03-27 17:31 UTC
Labels: bug, needs: issue template, has: pr
