### ISSUE TITLE
Inverted Flatlist(VirtualizedList) with specific conditions has rendering problem.

### ISSUE THREAD

**Issue by shine784** [necolas/react-native-web#1579] opened 2020-04-09 04:55 UTC
**The problem**
Flatlist(VirtualizedList) has problem specific conditions in Web
This list rendered the wrong range of index items, Sometimes It is rendered again constantly

**How to reproduce**
Simplified test case: https://snack.expo.io/@kunhee_lee/kunhee_lee_test

Steps to reproduce:
1. Just scroll up the list 
2. If you scroll up to near by 70~80 , you can see the malfunction
3. this problem is happend when renderitem has numberic height (ex: maybe upper than 40)  

**Expected behavior**
react-native-web/packages/react-native-web/src/vendor/reactnative/VirtualizeUtils/VirtualizeUtils.js
```
...
const leadFactor = 0.5; // Math.max(0, Math.min(1, velocity / 25 + 0.5));

  const fillPreference =
    velocity > 1 ? 'after' : velocity < -1 ? 'before' : 'none';

  const overscanBegin = Math.max(0,visibleBegin - (1 - leadFactor) * overscanLength, );
  const overscanEnd = Math.max(0, visibleEnd + leadFactor * overscanLength);

  const lastItemOffset = getFrameMetricsApprox(itemCount - 1).offset;
  if (lastItemOffset < overscanBegin) {
    // Entire list is before our overscan window
    return {
      first: Math.max(0, itemCount - 1 - maxToRenderPerBatch),
      last: itemCount - 1,
    };
  }
...
```
leadFactor(0.5) is not suitable value with some conditions
this makes the overscanBegin value bigger than 0 
so It cause the wrong retern with wrong first, last 
**If you fix this value leadFactor, this matter would is solved**
**I have tried to make correct formula for leadFactor**

**Environment (include versions). Did this work in previous versions?**
* React Native for Web (version):  0.12.2
* React (version): 16.9.0
* Browser: Chrome

**Comment by Sharcoux** [comment] 2020-08-04 17:34
Probably a duplicate of this: https://github.com/necolas/react-native-web/issues/1254

**Comment by azesmway** [comment] 2020-08-29 17:17
I solved this problem as follows

"react-native-web": "^0.13.9",
node_modules/react-native-web/dist/vendor/react-native/VirtualizedList/index.js

Added a second object on line 349
`_this._scrollMetrics2 = {
      contentLength: 0,
      dOffset: 0,
      dt: 10,
      offset: 0,
      timestamp: 0,
      velocity: 0,
      visibleLength: 0
    };`

in line 508 add 
`      _this._scrollMetrics = {
        contentLength: contentLength,
        timestamp: timestamp,
        velocity: velocity,
        visibleLength: visibleLength
      };

      _this._scrollMetrics2 = {
        contentLength: contentLength,
        dt: dt,
        dOffset: dOffset,
        offset: offset,
        timestamp: timestamp,
        velocity: velocity,
        visibleLength: visibleLength
      };`

and line 1265 
`var _this$_scrollMetrics2 = this._scrollMetrics2,`

and line 1278
`this._sentEndForContentLength = this._scrollMetrics2.contentLength;`

**Comment by awmiklovic** [comment] 2020-09-23 20:03
@azesmway This looks promising, but isn't working for me. I'm not sure that I'm implementing properly. Would you be able to supply a diff for the file?

**Comment by azesmway** [comment] 2020-09-23 20:14
@awmiklovic Hi! No problem, here's the whole file, you can compare.

"react-native-web": "^0.13.13"
PATH: node_modules/react-native-web/dist/vendor/react-native/VirtualizedList/index.js

[index.js.zip](https://github.com/necolas/react-native-web/files/5271644/index.js.zip)

**Comment by awmiklovic** [comment] 2020-09-23 20:51
Awesome, thank you! Here's the diff in case anyone else needs it:
```diff --git a/node_modules/react-native-web/dist/vendor/react-native/VirtualizedList/index.js b/node_modules/react-native-web/dist/vendor/react-native/VirtualizedList/index.js
index 8659501..da00709 100644
--- a/node_modules/react-native-web/dist/vendor/react-native/VirtualizedList/index.js
+++ b/node_modules/react-native-web/dist/vendor/react-native/VirtualizedList/index.js
@@ -346,6 +346,15 @@ function (_React$PureComponent) {
       velocity: 0,
       visibleLength: 0
     };
+    _this._scrollMetrics2 = {
+      contentLength: 0,
+      dOffset: 0,
+      dt: 10,
+      offset: 0,
+      timestamp: 0,
+      velocity: 0,
+      visibleLength: 0
+    };
     _this._scrollRef = null;
     _this._sentEndForContentLength = 0;
     _this._totalCellLength = 0;
@@ -506,6 +515,13 @@ function (_React$PureComponent) {
       }
 
       _this._scrollMetrics = {
+        contentLength: contentLength,
+        timestamp: timestamp,
+        velocity: velocity,
+        visibleLength: visibleLength
+      };
+
+      _this._scrollMetrics2 = {
         contentLength: contentLength,
         dt: dt,
         dOffset: dOffset,
@@ -1255,7 +1271,7 @@ function (_React$PureComponent) {
         getItemCount = _this$props10.getItemCount,
         onEndReached = _this$props10.onEndReached,
         onEndReachedThreshold = _this$props10.onEndReachedThreshold;
-    var _this$_scrollMetrics2 = this._scrollMetrics,
+    var _this$_scrollMetrics2 = this._scrollMetrics2,
         contentLength = _this$_scrollMetrics2.contentLength,
         visibleLength = _this$_scrollMetrics2.visibleLength,
         offset = _this$_scrollMetrics2.offset;
@@ -1268,7 +1284,7 @@ function (_React$PureComponent) {
     distanceFromEnd < onEndReachedThreshold * visibleLength && (this._hasDataChangedSinceEndReached || this._scrollMetrics.contentLength !== this._sentEndForContentLength)) {
       // Only call onEndReached once for a given dataset + content length.
       this._hasDataChangedSinceEndReached = false;
-      this._sentEndForContentLength = this._scrollMetrics.contentLength;
+      this._sentEndForContentLength = this._scrollMetrics2.contentLength;
       onEndReached({
         distanceFromEnd: distanceFromEnd
       });

**Comment by azesmway** [comment] 2020-09-23 20:54
@awmiklovic Did it work for you?

**Comment by awmiklovic** [comment] 2020-09-23 21:02
@azesmway Yes, nice work!

**Comment by Sharcoux** [comment] 2020-09-23 21:16
Do you think this could solve this issue too? https://github.com/necolas/react-native-web/issues/1254

Here is the [sandbox](https://codesandbox.io/s/flatlist-issue-rn-web-forked-hivbr)

**Comment by awmiklovic** [comment] 2020-09-23 22:21
@Sharcoux I believe so. This looks exactly like the bug I was running into.

**Comment by necolas** [comment] 2020-09-23 22:29
You should probably upstream this to react native as the code here is copy-paste from there

**Comment by tswicegood** [comment] 2020-10-12 21:21
Looks like this was originally reported in https://github.com/facebook/react-native/issues/28556 and the React Native team pointed @shine784 to react-native-web to report this. Not sure if they're open to a fix at that level, @necolas.

**Comment by necolas** [comment] 2020-10-12 22:33
I reopened that issue. If someone writes a PR for RN that improves compatibility on web without negatively effecting RN, I will help get the review prioritized

**Comment by buffaloDeveloper** [comment] 2022-01-11 15:10
@azesmway have you updated this to work with "react-native-web": "0.17.1"?  Looks like these changes are already there, but I'm seeing the same issue still.

**Comment by azesmway** [comment] 2022-01-12 09:30
> @azesmway have you updated this to work with "react-native-web": "0.17.1"? Looks like these changes are already there, but I'm seeing the same issue still.

Hi
I found solution easier

node_modules/react-native-web/dist/vendor/react-native/VirtualizedList/index.js

`if (!isVirtualizationDisabled) {
          // If we run this with bogus data, we'll force-render window {first: 0, last: 0},
          // and wipe out the initialNumToRender rendered elements.
          // So let's wait until the scroll view metrics have been set up. And until then,
          // we will trust the initialNumToRender suggestion
          if (visibleLength > 0 && contentLength > 0) {
            // If we have a non-zero initialScrollIndex and run this before we've scrolled,
            // we'll wipe out the initialNumToRender rendered elements starting at initialScrollIndex.
            // So let's wait until we've scrolled the view to the right place. And until then,
            // we will trust the initialScrollIndex suggestion.
            if (!_this.props.initialScrollIndex || _this._scrollMetrics.offset) {
              newState = computeWindowedRenderLimits(_this.props, state, _this._getFrameMetricsApprox, _this._scrollMetrics);
              newState.first = 0;  // <--- this change
             }
          }
        } else {`

**Comment by necolas** [comment] 2023-03-27 21:55
Closing this old issue because VirtualizedList will be developed exclusively out of the RN monorepo in the future. There may still be an issue in RNW, so feel free to create a new issue with latest info if needed.

**Closed by necolas** 2023-03-27 21:55 UTC
Labels: bug: react-native, project:react-native-web
