### ISSUE TITLE
Image SSR 

### ISSUE THREAD

**Issue by LantosTG** [necolas/react-native-web#1245] opened 2019-02-17 07:25 UTC
**The problem**
When rendering an \<Image\> in SSR it is rendered out as a \<div\> and then is hydrated by the client into a \<img\>. I have read https://github.com/necolas/react-native-web/issues/543 and saw that there was a change to
> When rendered on the server, images now include the 'src' and will be
downloaded by the browser rather than waiting for the client-side JS to
initiate image loading.
how ever the nature does not seem to be functioning correctly as of ^0.10.0.

**How to reproduce**
I have included a test case of the issue in the codesandbox bellow. I have just printed the result from the SSR to show it is a div rather then an image.
Simplified test case: https://codesandbox.io/s/4qv993qrmx

Steps to reproduce:
1. Create an app with SSR and Client side
2. Render a <Image> tag with uri
3. check page and it appears to work but if you disable javascript the image is a div.

**Expected behavior**
the html from the ReactDOMServer.renderToString should be an img tag but is a div tag and then is changed after the client side is hydrated.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.10.0
* React (version): 16.5.2
* Browser: Firefox/chrome

Additional: 
I am pretty sure your intention was to render out the \<Image\> as an \<img\> if the uri was passed rather then a div. Sorry If I am wrong. Thanks

**Comment by LantosTG** [comment] 2019-02-17 07:32
I have logged the issue,  but have closed it temporarily to make sure it wasn't any thing to do with my browser.

**Comment by LantosTG** [comment] 2019-02-17 07:47
Reopened. The issue became hidden on codesandbox due to the live rerendering of code sandbox.
by going directly to https://4qv993qrmx.codesandbox.io/ where it only renders once until you edit it will show the error.

**Comment by LantosTG** [comment] 2019-02-17 07:49
![screenshot from 2019-02-17 18-47-41](https://user-images.githubusercontent.com/39604275/52909960-b315e680-32e4-11e9-9717-f47aa0629fb7.png)

**Comment by necolas** [comment] 2019-02-17 10:32
Duplicate of #543 and reason for the current approach is explained by https://github.com/necolas/react-native-web/issues/543#issuecomment-310844971

If you want to SSR an image use the `defaultSource` prop.

**Closed by necolas** 2019-02-17 10:32 UTC
