### ISSUE TITLE
ScrollView: cannot stop default scroll event

### ISSUE THREAD

**Issue by Kinka** [necolas/react-native-web#477] opened 2017-05-14 13:41 UTC
just passing `scrollEnabled={false}` to the ScrollView would trigger such warning:
```
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
```
and the props.scrollEnabled used here of ScrollViewBase: 
```
  _handlePreventableScrollEvent = handler => {
    return e => {
      if (!this.props.scrollEnabled) {
        e.preventDefault();
      } else {
        if (handler) {
          handler(e);
        }
      }
    };
  };
```

**Comment by necolas** [comment] 2017-05-14 16:12
Not sure why a passive event listener is in use there when React doesn't support them

**Comment by necolas** [comment] 2017-06-01 15:25
Closing as I can't reproduce this in the storybook examples, and there isn't enough information to indicate that there's a bug in the library

**Comment by necolas** [comment] 2017-06-06 03:30
Tracked this down to a recent change in Chrome: https://www.chromestatus.com/features/5093566007214080

**Closed** 2017-06-11 21:42 UTC
Labels: bug
