### ISSUE TITLE
no such file or directory, open '..../node_modules/react-native-web/dist/exports/StyleSheet/StyleSheetValidation.js'

### ISSUE THREAD

**Issue by theankurkedia** [necolas/react-native-web#1507] opened 2019-12-18 13:00 UTC
React Native for Web (version): 0.11.7
React (version): 16.12.0
Browser: Chrome 79.0

Steps to reproduce:
1. Installed react-native-web.
2. set alias in babel

log: no such file or directory, open '..../node_modules/react-native-web/dist/exports/StyleSheet/StyleSheetValidation.js'

**Comment by necolas** [comment] 2019-12-18 13:55
Which file caused that error? Please include the full stack trace

**Comment by necolas** [comment] 2019-12-18 14:06
I can't reproduce this on codesandbox or locally, so I will close this until there is evidence of a problem in the library code.

**Closed by necolas** 2019-12-18 14:06 UTC
