### ISSUE TITLE
[babel-plugin-react-native-web] Mono repo and RNW transpilation issue

### ISSUE THREAD

**Issue by momsse** [necolas/react-native-web#982] opened 2018-06-01 19:47 UTC
**The problem**

Hello, thanks for all the hard work done on that poject !

I'm using `lerna` with yarn workspaces features on a project.

I encounter issues like `SyntaxError: Unexpected token export` due to the fact that babel will not transpile from the root `node_modules` (eg `node_modules/react-native-web/dist/exports/Platform/index.js`).

Since `react-native-web` also compile to `commonjs` on `dist/cjs/exports`. Is there a way to tell to `babel-plugin-react-native-web` to use that folder instead of `dist/exports/` ?

**How to reproduce**
Test case: 

Steps to reproduce:
1. Initiate a lerna repo + workspace
2. Add react-native-web on `packages/web` module for eg with `babel-plugin-react-native-web` as plugin on `.babelrc` file.
3. Run a basic jest test with any component using `react-native` primitive.

**Expected behavior**

To not have to transpile again `node_modules/react-native-web/dist/exports`.

**Environment (include versions). Did this work in previous versions?**

* OS: Mac OS X
* Device: Macbook Pro
* Browser: -
* React Native for Web (version): `0.7.3`
* React (version): `16.4.0`

**Comment by necolas** [comment] 2018-06-01 21:45
Duplicate of https://github.com/necolas/react-native-web/issues/961. Per the latest docs you probably don't need the Babel plugin if you're using a modern bundler that can process es modules and do tree shaking. But an option to have the plugin point to cjs modules will be included in 0.8.0

**Closed by necolas** 2018-06-01 21:45 UTC

**Comment by momsse** [comment] 2018-06-02 08:16
Thanks @necolas

I actually encountering this issue with jest test runner (my issue is not as precise, sorry). You're right for `production` output webpack to the work.

Will wait for that bump anyway !

**Comment by necolas** [comment] 2018-06-02 14:32
For jest, either try using the module mapper config to point at the RNW commonjs exports (dist/exports/cjs) or configure jest to use babel-jest to process js files. Hoping for one of these options to be automatically done in the next release too. It's a bit painful publishing a package with both module types!
