### ISSUE TITLE
focusedByKeyboard for Pressable

### ISSUE THREAD

**Issue by steida** [necolas/react-native-web#2074] opened 2021-06-29 11:09 UTC
**Is your feature request related to a problem? Please describe.**
The same reason why data-focusvisible-polyfill exists. If we implement a button with a custom focus, it's visible for a click which is confusing for non-keyboard users.

**Describe a solution you'd like**
An additional focusedByKeyboard prop or change focused behavior to match polyfill behavior.

**Describe alternatives you've considered**
Not using custom focus.

**Comment by necolas** [comment] 2021-09-29 21:34
Duplicate of #1849

**Closed by necolas** 2021-09-29 21:34 UTC
