### ISSUE TITLE
Navigator question

### ISSUE THREAD

**Issue by KalKhera** [necolas/react-native-web#212] opened 2016-09-22 08:42 UTC
Is navigator component something that could work on web? I am working on iOS/ windows uwp app and am very intrigued by web port of react native. Any plans to add navigator?

**Comment by RangerMauve** [comment] 2016-09-22 13:37
Seems like a duplicate of #207. Short answer: no

**Comment by necolas** [comment] 2016-09-22 17:30
Yes please see that other issue. Future version of Navigator should work on web. There may be other approaches too but I'm not focused on replicating navigation projects at the moment

**Closed by necolas** 2016-09-22 17:30 UTC
