### ISSUE TITLE
Touchable: onPress is triggered when scrolling at the top of a ScrollView

### ISSUE THREAD

**Issue by wjielim** [necolas/react-native-web#731] opened 2017-12-07 16:04 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
TouchableOpacity inside a ScrollView will be triggered if one try to scroll up while the ScrollView is already at its top. See the below gif for better understanding:

![scrollview touchable issue](https://user-images.githubusercontent.com/34246445/33724353-2dc2e4de-dbaa-11e7-90d8-1f16ab487ed6.gif)

This also happens to horizontal ScrollView. 

**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar (template:
https://glitch.com/edit/#!/react-native-web-playground).**

copy paste this code:

```
<ScrollView style={{backgroundColor: '#f1f2f3', flex: 1, height: Dimensions.get('window').height, width: Dimensions.get('window').width}}>
{
          (() => {for (let i=0; i < 10; i++){
            buttons.push(
              <TouchableOpacity onPress={() => {alert(`button ${i} Pressed!`)}}
                                style={{width: 300, height: 150, backgroundColor: 'blue', color: 'white', margin: 10}}>
                <Text>Button {i}</Text>
              </TouchableOpacity>
            )
          }})()
}

{buttons}
</ScrollView>
```

**What is the expected behavior?**

TouchableOpacity should not trigger onPress when it's inside a ScrollView (with height set to screen/window height) when scrolling under any circumstances.

**Environment (include versions). Did this work in previous versions?**

* OS: Windows
* Device: Microsoft Surface Pro 3
* Browser: Google Chrome v62.0.3202.94 (Official Build) (64-bit)
* React Native for Web (version): 0.1.16
* React (version): 16.2.0

**Comment by aizigao** [comment] 2018-01-19 04:45
same problem, mark

**Comment by jondkoon** [comment] 2018-01-23 20:44
I made a glitch to try and repro this and it seems to be working as expected when using a `ScrollView`:

View: https://giant-planet.glitch.me/
Edit: https://glitch.com/edit/#!/giant-planet?path=src/App/index.js:1:0

If you replace the `ScrollView` with a `View` then it fails as described

**Comment by necolas** [comment] 2018-01-27 18:54
I can't reproduce this issue either. Perhaps it is Windows-only, but that seems unlikely given the browser is Chrome.

**Comment by aizigao** [comment] 2018-01-30 03:23
@jondkoon @necolas it seem to bug with TouchableHighlight but not TouchableOpacity https://glitch.com/edit/#!/cultured-bracket
https://glitch.com/edit/#!/join/6adbab14-d2f7-4ebf-b7e1-c4e7cd49f28b

**Comment by necolas** [comment] 2018-02-03 02:06
I can actually reproduce this with both Touchables when you drag-down and release while still over the button. On native, the scrollview becomes the responder as soon as you start to drag after pressing on a touchable. On web, the touchable remains the responder.

**Comment by necolas** [comment] 2018-02-15 02:11
I think I understand the root of the issue. In React Native, `ScrollView` will trigger `onScroll` events if you're dragging down when at the top of the scroll view - this allows the responder system to transfer the responder grant from the touchable back to the scroll view. But the web stops dispatching scroll events when `scrollTop === 0`, so the responder system leaves the touchable as the responder.

This issue goes away when you dispatch a scroll event for any `touchmove` that occurs within a `ScrollView` when `scrollTop === 0`. But I will need to investigate a more sophisticated solution that accounts for drag direction, and take some time understanding what problems this approach might introduce.

**Comment by Kinka** [comment] 2018-05-16 10:10
How is going on here? I encounter this again. Touchable inside ScrollView will trigger onPress unexpectedly when scrolling.

**Comment by mho79** [comment] 2018-07-18 09:01
has there been any progress on this issue? or a workaround?

**Comment by hushicai** [comment] 2018-08-25 06:29
I think custom scroller that supports momentum scroll event  will solve this problem.

**Comment by MoOx** [comment] 2018-12-31 15:17
I think I found something that might help to debug this. While investigating for #829, I tried to wrap my app with a ScrollView without any actual scroll (no specific height or flex). A sort of useless ScrollView, but not that useless as touch events are still triggered. It's just that scroll is never fired.
And with this setup, I experienced some weird cases, while touching/moving. I didn't always get a cancel for a given touch. I am not able yet to reproduce but playing with on mobile clearly show that the opacity effect is not always canceled while scrolling...  https://v84xmm7l37.codesandbox.io/

We can clearly see most scroll trigger onPress, but not all. And we know it before releasing the finger.

![demo](https://user-images.githubusercontent.com/157534/50562760-2eacdb80-0d17-11e9-9bc1-f5589db9b54f.gif)

**Comment by necolas** [comment] 2019-01-03 21:22
Closing this issue so we can coordinate findings and solutions in #1219

**Closed by necolas** 2019-01-03 21:22 UTC
Labels: bug

**Comment by Diaa-Ghonim** [comment] 2023-09-09 20:23
@necolas this issue is still happening with me 

I use this release 0.11.7 
and I upgraded to 0.13.0 and 0.14.0 and it is still happening with me.

any one solved it here??

**Comment by necolas** [comment] 2023-09-11 18:42
Update to 0.19.
