### ISSUE TITLE
Touchable issues

### ISSUE THREAD

**Issue by necolas** [necolas/react-native-web#1219] opened 2019-01-03 21:22 UTC
**The problem**

The overall issue appears to be that a) events don't always occurs in the same order, which means the responder is not transferred correctly, b) mouse move events during a touch can cause the responder to be terminated, and c) scroll events are not always fired in situations where they are expected in React Native.

There are problems with the responder event system setup that are covered by these issues:

## #693 

https://glitch.com/edit/#!/statuesque-bedbug

> locationX is relative to the element on which the native event occurred but not the element which the responder event is attached.

## #731

https://glitch.com/edit/#!/cultured-bracket

> In React Native, ScrollView will trigger onScroll events if you're dragging down when at the top of the scroll view - this allows the responder system to transfer the responder grant from the touchable back to the scroll view. But the web stops dispatching scroll events when scrollTop === 0, so the responder system leaves the touchable as the responder. The reported issue goes away when ScrollView dispatches a DOM scroll event after it receives a touchmove that occurs when scrollTop === 0.

## #829 

> There are 2 significant issues with using `Touchable*` components within an app that relies on the `document.body` (rather than `ScrollView`) being the root scroller. I believe the root cause of both issues is that the body is not part of the responder system, which `Touchable` and `ScrollView` rely on to coordinate transfer of the responder grant.

## #1164

https://codesandbox.io/s/6njwzqojnr

> TouchableOpacity will trigger another component at the same location when changing views (if second component is an "<input>" or "<TextInput>")

## #1124 

> Across multiple browsers, if you hold the mouse very still onPress triggers, but if the mouse is in motion onPress does not work.

**Context**

Part of the solution may related to producing the correct events (as can be inferred from React Native). This might involve changes to the event filtering logic in the REP, and the scroll event logic in ScrollView.

* [Responder Event Plugin](https://github.com/necolas/react-native-web/blob/0.9.13/packages/react-native-web/src/modules/ResponderEventPlugin/index.js)
* [ScrollResponder](https://github.com/necolas/react-native-web/blob/0.9.13/packages/react-native-web/src/modules/ScrollResponder/index.js)
* [ScrollView](https://github.com/necolas/react-native-web/blob/0.9.13/packages/react-native-web/src/exports/ScrollView/index.js)

**Related incomplete patches**

Attempts to patch these problems.

* https://github.com/necolas/react-native-web/pull/997/files
* https://github.com/rxrossi/react-native-web/commit/1e3eb7fdf1ccb9e29abda83ae8482968e50d49b2

**Comment by tafelito** [comment] 2019-01-16 23:19
@necolas what's missing on the 2 solutions you mentioned above?

I don't see this happening at twitter, is this an issue from the latest versions of RNW, are you doing anything different there?

**Comment by tafelito** [comment] 2019-01-16 23:46
For us this also happens outside a ScrollView. We are avoiding it in some places just using preventDefault but that just also a hack and it doesn't even work in every case




________________________________

**Comment by viggyfresh** [comment] 2019-01-18 07:00
Hi @necolas,

Just wanted to follow up on @aligg's comment in #1124 (see https://github.com/necolas/react-native-web/issues/1124#issuecomment-450954401) - we ended up solving our issue! For posterity: we had inadvertently mixed our metaphors and wrapped a bunch of RNW components inside a `div` with `overflow-y` set to `scroll`; when we replaced this with a RNW `ScrollView`, all of our problems magically went away! I'm not at all familiar with the responder event system, but I presume this particular blend of web and RNW components isn't supported (or wise).

**Comment by RichardLindhout** [comment] 2019-03-04 12:13
@necolas Maybe we can listen to a normal click event of the browser instead of onTouchStart etc.

**Comment by EyMaddis** [comment] 2019-05-09 18:35
@RichardLindhout 
I use custom touchables right now and it works by using something like this:

```js
<TouchableOpacity
          ...
          {...(Platform.OS === 'web'
            ? {
                // When scrolling the document body, the touchables might be triggered
                // see  https://github.com/necolas/react-native-web/issues/1219
                onClick: this.onPress,
              }
            : {
                onClick: this.onPress,
              })}
/>
```

**Comment by loudwinston** [comment] 2019-06-10 16:02
@EyMaddis good tip!  We applied this as a monkey-patch for Touchable components by using webpack `NormalModuleReplacementPlugin` so we don't have to apply this ternary all over our app

## webpack.config.js
```javascript
plugins: [
  new webpack.NormalModuleReplacementPlugin(
    /^react-native$/,
    path.resolve(__dirname, './src/web/react-native-web.tsx')
  )
]
```


## `react-native-web.tsx`

```javascript
import React from 'react'
import * as ReactNativeWeb from 'react-native-web'

const createTouchable = (Touchable) => (props: any) => {
  const { onPress, ...restProps } = props
  return (
    <Touchable {...restProps} onClick={onPress} />
  )
}

export * from 'react-native-web'

export const TouchableOpacity = createTouchable(ReactNativeWeb.TouchableOpacity)
export const TouchableWithoutFeedback = createTouchable(ReactNativeWeb.TouchableWithoutFeedback)
// etc

```

**Comment by tafelito** [comment] 2019-06-10 17:40
one problem I see with that solution is that you manually need to handle propagation. If you have a Touchable inside another touchable, the onPress only gets called once. Using onClick you have to stop propagation depending on your use case it might just work adding in to the onClick event

**Comment by EyMaddis** [comment] 2019-06-27 00:31
The touchable problem with touchables triggering on scrollY=0 boils down to this line:

https://github.com/necolas/react-native-web/blob/master/packages/react-native-web/src/modules/ScrollResponder/index.js#L336 (`scrollResponderIsAnimating`) 
as it controls `scrollResponderHandleStartShouldSetResponderCapture`.

If I understand it correctly the problem is that the `touchstart` event fires first and then scroll. But touchstart was already triggered and grants the handling to the touchable...
Once the browser triggers scroll, the touchable handling should be terminated and the scrollview should seize control.

**Comment by jorgechen** [comment] 2019-07-20 01:54
Noticed that on certain mobile browsers like iOS Safari, scrolling will accidentally click.  Is this the same issue that you're describing @EyMaddis ?

**Comment by EyMaddis** [comment] 2019-07-24 15:53
@jorgechen Yes, see https://github.com/necolas/react-native-web/issues/731

**Comment by andreassavva** [comment] 2019-07-29 12:20
About #1124 it only happens when I have scrolled down below approximately 50 pixels. If I am at the top of the page, the onPress event is being called as it should. If I first scroll below 50 pixels or more, click down inside the TouchableOpacity and then move the mouse (still inside the TouchableOpacity component), then the press event is being released and the onPress event is not called when I release the mouse click.

Anyone that can shed some light on where in react-native-web this is happening? It would help me search for a way to fix this

**Comment by andreassavva** [comment] 2019-07-30 13:11
I fixed #1124 . In `Touchable/index.js` the touch from the native event is extracted in the `touchableHandleResponderMove` function and `pageX` and `pageY` are received from it. These two attributes give the x and y positions in the whole page, which means that the scrolled pixels are added to them.

Getting `clientX` and `clientY` from `touch` instead of `pageX` and `pageY` fixes this issue for me.

**Comment by brunolemos** [comment] 2019-09-29 06:24
Is there any workaround for the touchable press getting triggered if I scroll and release the finger after the scroll stops?

This is hurting the ux of my app.

![](https://user-images.githubusercontent.com/157534/50562760-2eacdb80-0d17-11e9-9bc1-f5589db9b54f.gif)

cc @MoOx

**Comment by jorgechen** [comment] 2019-09-30 00:50
@brunolemos Have you tried the method suggested by @EyMaddis ? That solution has worked for me until an official fix.

By the way, good work on DevHub and hope you continue writing dev articles. Obrigado.

**Comment by brunolemos** [comment] 2019-10-02 23:35
I ended up using a different workaround. I have a `Touchable.tsx` component and I check the `pageX` and `pageY` values from the press events, and if the user moved the finger I assume it was a scroll and cancel the press event. Seems to work great.

```tsx
const pressInPagePointRef = useRef({ x: 0, y: 0 })

const onPressIn = useCallback<NonNullable<TouchableProps['onPressIn']>>(
  e => {
    pressInPagePointRef.current = {
      x: e.nativeEvent.pageX,
      y: e.nativeEvent.pageY,
    }

    if (_onPressIn) _onPressIn(e)
  },
  [_onPressIn],
)

const onPressOut = useCallback<NonNullable<TouchableProps['onPressOut']>>(
  e => {
    if (_onPressOut) _onPressOut(e)

    const [x, y] = [e.nativeEvent.pageX, e.nativeEvent.pageY]
    if (
      Math.abs(pressInPagePointRef.current.x - x) > 1 ||
      Math.abs(pressInPagePointRef.current.y - y) > 1
    ) {
      e.preventDefault()
    }
  },
  [_onPressOut],
)

const onPress = useCallback<NonNullable<TouchableProps['onPress']>>(
  e => {
    if (e.isDefaultPrevented()) return
    if (_onPress) _onPress(e)
  },
  [_onPress],
)
```

**Comment by necolas** [comment] 2019-11-27 00:44
I'm working on a user-space replacement for the responder system that aims to resolve these issues and drop the dependency on ReactDOM's `unstable-native-dependencies` module.

**Comment by brunolemos** [comment] 2019-11-27 15:59
> drop the dependency on ReactDOM's unstable-native-dependencies module.

Nice. Would that unlock preact support? 

Ref: #330
Ref: https://github.com/preactjs/preact/issues/1830

**Comment by necolas** [comment] 2019-11-27 18:53
Maybe!

**Comment by mschipperheyn** [comment] 2019-12-04 17:04
@necolas achievement unlocked: **Guru**!

**Comment by necolas** [comment] 2019-12-18 11:37
FYI I tried PreactX in my hooks branch (which has the in-progress responder replacement).
Preact is rendering the benchmarks 50% slower than React.
And Preact has a bug that prevents the responder hook's event handlers from ever being run.

**Comment by marvinhagemeister** [comment] 2020-01-23 07:49
@necolas Can you file an issue for us over at the Preact repo? We'd love to get to the bottom of this :+1:

**Comment by jfrolich** [comment] 2020-02-24 10:10
@necolas: Do you have a recommendation how to handle the current issue with window scrolling being broken? Are you open to have a temporary workaround in the stable RNW, before the responder system rewrite that fixes the scrolling issue has landed. (Perhaps a fix that does not handle all cases, but makes Touchables usable in a window scroll environment). Or do you foresee the new responder system landing soon-ish? Or would you recommend to do a patch-package for now?

**Comment by xiaods** [comment] 2020-03-08 08:44
$ npm ls react-native-web
em@93.0.0 /Users/xiaods/Documents/Code/em
└── react-native-web@0.12.0 

xiaods at xiaodeshi in ~/Documents/code/em on  (dev)
$ npm ls react-scripts
em@93.0.0 /Users/xiaods/Documents/Code/em
└── react-scripts@1.1.5 

in a react-native-web project. 

1、create multigesture component from react.  use react-native-web packge
// requires installation of react-dom and react-native-web
import { PanResponder } from 'react-native'

when came with react-scripts@1.1.5 , it works like a charm.

when upgrade the react-script > 2, the PanResponder will can't work in iOS mobile.

**Comment by EyMaddis** [comment] 2020-03-10 14:51
@jfrolich Could you try this PR? https://github.com/necolas/react-native-web/pull/1472

**Comment by jfrolich** [comment] 2020-03-11 06:40
@EyMaddis: Will try! Looks like a good solution! I see that it's conflicting now with master?

**Comment by necolas** [comment] 2020-04-12 19:55
Please try version `0.0.0-33f8505d6` (a canary release) and let me know if the problem is resolved. See  #1538

**Comment by rxb** [comment] 2020-04-14 03:12
I had the same / similar problem as @jfrolich which brought me to this issue. Version `0.0.0-33f8505d6` totally fixed it for me. Thanks for all your work on this!

**Comment by jfrolich** [comment] 2020-04-15 10:44
I tried different solutions, and they didn't really solve the problem. The new fix by @necolas works perfectly however! Only now reanimated/react-native-gesture-handler are breaking, probably because this is such a big change in the internals.

**Comment by necolas** [comment] 2020-04-15 15:50
Are they breaking on `findNodeHandle` calls? That API is going away in React Native/DOM as it doesn't work with functional components or concurrent mode

**Comment by jfrolich** [comment] 2020-04-16 03:26
> Are they breaking on `findNodeHandle` calls? That API is going away in React Native/DOM as it doesn't work with functional components or concurrent mode

Yes precisely that. What API is replacing that?

**Comment by necolas** [comment] 2020-04-16 03:29
React refs to host nodes should be used. Facebook and React Native itself have mostly migrated off those APIs already. https://reactjs.org/docs/react-dom.html#finddomnode

**Comment by jfrolich** [comment] 2020-04-16 03:37
> React refs to host nodes should be used. Facebook and React Native itself have mostly migrated off those APIs already. https://reactjs.org/docs/react-dom.html#finddomnode

Gotcha, that's what I thought as well 👍

**Closed** 2020-06-26 21:56 UTC
Labels: bug

**Comment by Maker-Mark** [comment] 2021-08-16 20:58
Still seeing this issue!
