### ISSUE TITLE
Warning: Failed prop type: Invalid props.style key `pointerEvents` supplied to `View`.

### ISSUE THREAD

**Issue by Josema** [necolas/react-native-web#1314] opened 2019-03-29 10:19 UTC
Getting this error when applying that property.
```
Warning: Failed prop type: Invalid props.style key `pointerEvents` supplied to `View`.
```

But is a valid property for View component.
https://facebook.github.io/react-native/docs/view

**Comment by necolas** [comment] 2019-03-29 14:07
Duplicate of https://github.com/necolas/react-native-web/issues/1293

**Closed by necolas** 2019-03-29 14:07 UTC
