### ISSUE TITLE
AsyncStorage not available in RNW 0.13.7 expo/ after update to expo sdk 39.0

### ISSUE THREAD

**Issue by aguilared** [necolas/react-native-web#1748] opened 2020-09-22 14:32 UTC
**The problem**
AsyncStorage not available in RNW 0.13.7 

**How to reproduce**
Run in web
Module not found: Can't resolve 'react-native-web/dist/exports/AsyncStorage

**Expected behavior**
No Run in Web, Ok in Smartphone

* React Native for Web (version): TBC
RNW 0.13.7

**Comment by EvanBacon** [comment] 2020-09-22 14:37
Duplicate of https://github.com/necolas/react-native-web/issues/1515

**Closed** 2020-09-22 14:56 UTC
