### ISSUE TITLE
Animating `shadowOffset` doesn’t work

### ISSUE THREAD

**Issue by swashcap** [necolas/react-native-web#688] opened 2017-10-18 21:47 UTC
**Do you want to request a *feature* or report a *bug*?**

🐛 Bug!

**What is the current behavior?**

Animating `shadowOffset`’s `height` or `width` doesn’t work.

Example code (see below for full demo link):

```js
class Hello extends React.Component {}
  constructor(p, c) {
    super(p, c);
    this.state = {
      shadow: new ReactNative.Animated.Value(0)
    };
  }
  // ...
  render() {
    return (
      <ReactNative.Animated.View style={{
        shadowOffset: {
          height: this.state.shadow.interpolate({
            inputRange: [0, 1],
            outputRange: [2, 10]
          }),
          width: 0
        }
      }}
      >
        {/* ... */}
      </ReactNative.Animated.View>
    );
  }
}
```

This error manifests in a `JSON.stringify` error logged to the console:

```
Warning: Failed prop type: cyclic object value
    in View (created by AnimatedComponent)
    in AnimatedComponent (at Button.js:92)
    in TouchableWithoutFeedback (at Button.js:85)
    in Button (at index.js:12)
    in div (created by View)
    in View (at index.js:11)
```

This comes from [`src/propTypes/createStrictShapeTypeChecker`](https://github.com/necolas/react-native-web/blob/3870445b7e86562a7dcfa5f8d6c11b52433838c3/src/propTypes/createStrictShapeTypeChecker.js#L57)’s `JSON.stringify` call. The real problem is the propTypes validation error:

![errorz](https://user-images.githubusercontent.com/1858316/31744315-37d5df1c-b413-11e7-9079-d32cbbc2ac7d.jpg)

It looks like `props.style.shadowOffset.height` is an `AnimatedInterpolation` instance, and its current value isn't being assigned to the `height` property. I dug around looking for how animation classes are passed to [animated](https://github.com/animatedjs/animated) and retrieved. Can we fix the [“FlattenStyle” injection](https://github.com/swashcap/react-native-web/blob/master/src/apis/Animated/index.js#L19) so animated can detect/interpolate its deeply nested classes?

**If the current behavior is a bug, please provide the steps to reproduce and
if a minimal demo of the problem via Glitch or similar (template:
https://glitch.com/edit/#!/react-native-web-playground).**

I made [an example project](https://github.com/swashcap/react-native-shadow-animation) to show the bug. Specifically, check out [swashcap/react-native-shadow-animation/Button.js](https://github.com/swashcap/react-native-shadow-animation/blob/4371f118f546b7a267ffe5049c54dd2eded5cbaf/Button.js#L100-L106)

**What is the expected behavior?**

I expect animating `shadowOffset`’s `height` and `width` would work, and display similar to react-native ([see example project GIF](https://github.com/swashcap/react-native-shadow-animation/blob/master/img/iphone-simulator.gif)).

**Environment (include versions). Did this work in previous versions?**

* OS: macOS 10.12.16
* Device: 15" rMBP
* Browser: Firefox 56.0
* React Native for Web (version): 0.1.9
* React (version): 16.0.0-alpha.12

**Comment by swashcap** [comment] 2017-10-18 22:39
Related: animatedjs/animated#55

**Comment by swashcap** [comment] 2017-10-18 22:50
This is a duplicate of #353. Bad issue browsing on my part. I agree, this _likely_ belongs in animated, but `shadowOffset` could be an exception as it’s react-native specific. What would you think about manually mapping the `shadowOffset` object to `box-shadow` to fix the issue?

**Comment by necolas** [comment] 2017-10-18 23:49
Does this work in `react-native`?

**Comment by swashcap** [comment] 2017-10-19 00:43
Yeah, totally does ([GIF from demo](https://github.com/swashcap/react-native-shadow-animation/blob/master/img/iphone-simulator.gif)).

**Comment by necolas** [comment] 2017-10-19 01:32
Yeah the problem is upstream in the `animatedjs/animated` library as per #55. You can see that the React Native implementation handles the `shadowOffset`.

[AnimatedStyle](https://github.com/animatedjs/animated/blob/master/src/AnimatedStyle.js) (`animatedjs/animated`): 

[AnimatedStyle](https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/Libraries/Animated/src/nodes/AnimatedStyle.js#L37) (`facebook/react-native`)

Since the `animated` package is not well maintained and missing most recent changes, I will probably have to go back to copy-pasting the `Animated` implementation out of React Native. Perhaps one day the RN project can publish the animated package separately too.

**Comment by swashcap** [comment] 2017-10-19 16:52
Hmm, I see. Looks react-native has [a package.json and build process](https://github.com/facebook/react-native/tree/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/Libraries/Animated/release), but it's not being built/published with the rest of react-native. I’ll open an issue and see if they're open to fixing their build script and publishing react-animated alongside react-native.

**Comment by necolas** [comment] 2017-11-15 22:52
Closing / folding this issue into #716

**Closed by necolas** 2017-11-15 22:52 UTC
